/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.NewSubscriber.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the useraccount service. Represents a row in the &quot;NS_useraccount&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.NewSubscriber.model.impl.useraccountModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.NewSubscriber.model.impl.useraccountImpl}.
 * </p>
 *
 * @author Shruthi
 * @see useraccount
 * @see com.NewSubscriber.model.impl.useraccountImpl
 * @see com.NewSubscriber.model.impl.useraccountModelImpl
 * @generated
 */
public interface useraccountModel extends BaseModel<useraccount> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a useraccount model instance should use the {@link useraccount} interface instead.
	 */

	/**
	 * Returns the primary key of this useraccount.
	 *
	 * @return the primary key of this useraccount
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this useraccount.
	 *
	 * @param primaryKey the primary key of this useraccount
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the useraccount ID of this useraccount.
	 *
	 * @return the useraccount ID of this useraccount
	 */
	public long getUseraccountId();

	/**
	 * Sets the useraccount ID of this useraccount.
	 *
	 * @param useraccountId the useraccount ID of this useraccount
	 */
	public void setUseraccountId(long useraccountId);

	/**
	 * Returns the company ID of this useraccount.
	 *
	 * @return the company ID of this useraccount
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this useraccount.
	 *
	 * @param companyId the company ID of this useraccount
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the first name of this useraccount.
	 *
	 * @return the first name of this useraccount
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this useraccount.
	 *
	 * @param firstName the first name of this useraccount
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this useraccount.
	 *
	 * @return the last name of this useraccount
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this useraccount.
	 *
	 * @param lastName the last name of this useraccount
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the e mail of this useraccount.
	 *
	 * @return the e mail of this useraccount
	 */
	@AutoEscape
	public String getEMail();

	/**
	 * Sets the e mail of this useraccount.
	 *
	 * @param eMail the e mail of this useraccount
	 */
	public void setEMail(String eMail);

	/**
	 * Returns the phone no of this useraccount.
	 *
	 * @return the phone no of this useraccount
	 */
	@AutoEscape
	public String getPhoneNo();

	/**
	 * Sets the phone no of this useraccount.
	 *
	 * @param phoneNo the phone no of this useraccount
	 */
	public void setPhoneNo(String phoneNo);

	/**
	 * Returns the major of this useraccount.
	 *
	 * @return the major of this useraccount
	 */
	@AutoEscape
	public String getMajor();

	/**
	 * Sets the major of this useraccount.
	 *
	 * @param major the major of this useraccount
	 */
	public void setMajor(String major);

	/**
	 * Returns the cgpa of this useraccount.
	 *
	 * @return the cgpa of this useraccount
	 */
	@AutoEscape
	public String getCgpa();

	/**
	 * Sets the cgpa of this useraccount.
	 *
	 * @param cgpa the cgpa of this useraccount
	 */
	public void setCgpa(String cgpa);

	/**
	 * Returns the role of this useraccount.
	 *
	 * @return the role of this useraccount
	 */
	@AutoEscape
	public String getRole();

	/**
	 * Sets the role of this useraccount.
	 *
	 * @param role the role of this useraccount
	 */
	public void setRole(String role);

	/**
	 * Returns the password of this useraccount.
	 *
	 * @return the password of this useraccount
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this useraccount.
	 *
	 * @param password the password of this useraccount
	 */
	public void setPassword(String password);

	/**
	 * Returns the asurite ID of this useraccount.
	 *
	 * @return the asurite ID of this useraccount
	 */
	@AutoEscape
	public String getAsuriteId();

	/**
	 * Sets the asurite ID of this useraccount.
	 *
	 * @param asuriteId the asurite ID of this useraccount
	 */
	public void setAsuriteId(String asuriteId);

	/**
	 * Returns the level of this useraccount.
	 *
	 * @return the level of this useraccount
	 */
	@AutoEscape
	public String getLevel();

	/**
	 * Sets the level of this useraccount.
	 *
	 * @param level the level of this useraccount
	 */
	public void setLevel(String level);

	/**
	 * Returns the sex of this useraccount.
	 *
	 * @return the sex of this useraccount
	 */
	@AutoEscape
	public String getSex();

	/**
	 * Sets the sex of this useraccount.
	 *
	 * @param sex the sex of this useraccount
	 */
	public void setSex(String sex);

	/**
	 * Returns the userapproved of this useraccount.
	 *
	 * @return the userapproved of this useraccount
	 */
	public boolean getUserapproved();

	/**
	 * Returns <code>true</code> if this useraccount is userapproved.
	 *
	 * @return <code>true</code> if this useraccount is userapproved; <code>false</code> otherwise
	 */
	public boolean isUserapproved();

	/**
	 * Sets whether this useraccount is userapproved.
	 *
	 * @param userapproved the userapproved of this useraccount
	 */
	public void setUserapproved(boolean userapproved);

	/**
	 * Returns the date added of this useraccount.
	 *
	 * @return the date added of this useraccount
	 */
	public Date getDateAdded();

	/**
	 * Sets the date added of this useraccount.
	 *
	 * @param dateAdded the date added of this useraccount
	 */
	public void setDateAdded(Date dateAdded);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(useraccount useraccount);

	public int hashCode();

	public CacheModel<useraccount> toCacheModel();

	public useraccount toEscapedModel();

	public String toString();

	public String toXmlString();
}