/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.asu.poly.iProjects.student.model.impl;

import com.asu.poly.iProjects.student.model.availability;
import com.asu.poly.iProjects.student.service.availabilityLocalServiceUtil;

import com.liferay.portal.kernel.exception.SystemException;

/**
 * The extended model base implementation for the availability service. Represents a row in the &quot;poly_availability&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link availabilityImpl}.
 * </p>
 *
 * @author Shruthi
 * @see availabilityImpl
 * @see com.asu.poly.iProjects.student.model.availability
 * @generated
 */
public abstract class availabilityBaseImpl extends availabilityModelImpl
	implements availability {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a availability model instance should use the {@link availability} interface instead.
	 */
	public void persist() throws SystemException {
		if (this.isNew()) {
			availabilityLocalServiceUtil.addavailability(this);
		}
		else {
			availabilityLocalServiceUtil.updateavailability(this);
		}
	}
}