/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.asu.poly.iProjects.student.service.base;

import com.asu.poly.iProjects.student.model.availability;
import com.asu.poly.iProjects.student.service.availabilityLocalService;
import com.asu.poly.iProjects.student.service.availabilityService;
import com.asu.poly.iProjects.student.service.persistence.availabilityPersistence;
import com.asu.poly.iProjects.student.service.persistence.preferencesPersistence;
import com.asu.poly.iProjects.student.service.persistence.studentPersistence;
import com.asu.poly.iProjects.student.service.preferencesLocalService;
import com.asu.poly.iProjects.student.service.preferencesService;
import com.asu.poly.iProjects.student.service.studentLocalService;
import com.asu.poly.iProjects.student.service.studentService;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.BaseServiceImpl;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import javax.sql.DataSource;

/**
 * The base implementation of the availability remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.asu.poly.iProjects.student.service.impl.availabilityServiceImpl}.
 * </p>
 *
 * @author Shruthi
 * @see com.asu.poly.iProjects.student.service.impl.availabilityServiceImpl
 * @see com.asu.poly.iProjects.student.service.availabilityServiceUtil
 * @generated
 */
public abstract class availabilityServiceBaseImpl extends BaseServiceImpl
	implements availabilityService, IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.asu.poly.iProjects.student.service.availabilityServiceUtil} to access the availability remote service.
	 */

	/**
	 * Returns the availability local service.
	 *
	 * @return the availability local service
	 */
	public availabilityLocalService getavailabilityLocalService() {
		return availabilityLocalService;
	}

	/**
	 * Sets the availability local service.
	 *
	 * @param availabilityLocalService the availability local service
	 */
	public void setavailabilityLocalService(
		availabilityLocalService availabilityLocalService) {
		this.availabilityLocalService = availabilityLocalService;
	}

	/**
	 * Returns the availability remote service.
	 *
	 * @return the availability remote service
	 */
	public availabilityService getavailabilityService() {
		return availabilityService;
	}

	/**
	 * Sets the availability remote service.
	 *
	 * @param availabilityService the availability remote service
	 */
	public void setavailabilityService(availabilityService availabilityService) {
		this.availabilityService = availabilityService;
	}

	/**
	 * Returns the availability persistence.
	 *
	 * @return the availability persistence
	 */
	public availabilityPersistence getavailabilityPersistence() {
		return availabilityPersistence;
	}

	/**
	 * Sets the availability persistence.
	 *
	 * @param availabilityPersistence the availability persistence
	 */
	public void setavailabilityPersistence(
		availabilityPersistence availabilityPersistence) {
		this.availabilityPersistence = availabilityPersistence;
	}

	/**
	 * Returns the preferences local service.
	 *
	 * @return the preferences local service
	 */
	public preferencesLocalService getpreferencesLocalService() {
		return preferencesLocalService;
	}

	/**
	 * Sets the preferences local service.
	 *
	 * @param preferencesLocalService the preferences local service
	 */
	public void setpreferencesLocalService(
		preferencesLocalService preferencesLocalService) {
		this.preferencesLocalService = preferencesLocalService;
	}

	/**
	 * Returns the preferences remote service.
	 *
	 * @return the preferences remote service
	 */
	public preferencesService getpreferencesService() {
		return preferencesService;
	}

	/**
	 * Sets the preferences remote service.
	 *
	 * @param preferencesService the preferences remote service
	 */
	public void setpreferencesService(preferencesService preferencesService) {
		this.preferencesService = preferencesService;
	}

	/**
	 * Returns the preferences persistence.
	 *
	 * @return the preferences persistence
	 */
	public preferencesPersistence getpreferencesPersistence() {
		return preferencesPersistence;
	}

	/**
	 * Sets the preferences persistence.
	 *
	 * @param preferencesPersistence the preferences persistence
	 */
	public void setpreferencesPersistence(
		preferencesPersistence preferencesPersistence) {
		this.preferencesPersistence = preferencesPersistence;
	}

	/**
	 * Returns the student local service.
	 *
	 * @return the student local service
	 */
	public studentLocalService getstudentLocalService() {
		return studentLocalService;
	}

	/**
	 * Sets the student local service.
	 *
	 * @param studentLocalService the student local service
	 */
	public void setstudentLocalService(studentLocalService studentLocalService) {
		this.studentLocalService = studentLocalService;
	}

	/**
	 * Returns the student remote service.
	 *
	 * @return the student remote service
	 */
	public studentService getstudentService() {
		return studentService;
	}

	/**
	 * Sets the student remote service.
	 *
	 * @param studentService the student remote service
	 */
	public void setstudentService(studentService studentService) {
		this.studentService = studentService;
	}

	/**
	 * Returns the student persistence.
	 *
	 * @return the student persistence
	 */
	public studentPersistence getstudentPersistence() {
		return studentPersistence;
	}

	/**
	 * Sets the student persistence.
	 *
	 * @param studentPersistence the student persistence
	 */
	public void setstudentPersistence(studentPersistence studentPersistence) {
		this.studentPersistence = studentPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return availability.class;
	}

	protected String getModelClassName() {
		return availability.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = availabilityPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = availabilityLocalService.class)
	protected availabilityLocalService availabilityLocalService;
	@BeanReference(type = availabilityService.class)
	protected availabilityService availabilityService;
	@BeanReference(type = availabilityPersistence.class)
	protected availabilityPersistence availabilityPersistence;
	@BeanReference(type = preferencesLocalService.class)
	protected preferencesLocalService preferencesLocalService;
	@BeanReference(type = preferencesService.class)
	protected preferencesService preferencesService;
	@BeanReference(type = preferencesPersistence.class)
	protected preferencesPersistence preferencesPersistence;
	@BeanReference(type = studentLocalService.class)
	protected studentLocalService studentLocalService;
	@BeanReference(type = studentService.class)
	protected studentService studentService;
	@BeanReference(type = studentPersistence.class)
	protected studentPersistence studentPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private availabilityServiceClpInvoker _clpInvoker = new availabilityServiceClpInvoker();
}