/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.StudentAvailability.slayer.model.impl;

import com.StudentAvailability.slayer.model.SASstudent;
import com.StudentAvailability.slayer.model.SASstudentModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the SASstudent service. Represents a row in the &quot;SAS_SASstudent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.StudentAvailability.slayer.model.SASstudentModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SASstudentImpl}.
 * </p>
 *
 * @author Purva
 * @see SASstudentImpl
 * @see com.StudentAvailability.slayer.model.SASstudent
 * @see com.StudentAvailability.slayer.model.SASstudentModel
 * @generated
 */
public class SASstudentModelImpl extends BaseModelImpl<SASstudent>
	implements SASstudentModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a s a sstudent model instance should use the {@link com.StudentAvailability.slayer.model.SASstudent} interface instead.
	 */
	public static final String TABLE_NAME = "SAS_SASstudent";
	public static final Object[][] TABLE_COLUMNS = {
			{ "studentid", Types.BIGINT },
			{ "ASUId", Types.VARCHAR },
			{ "mon8to9", Types.VARCHAR },
			{ "mon9to10", Types.VARCHAR },
			{ "mon10to11", Types.VARCHAR },
			{ "mon11to12", Types.VARCHAR },
			{ "mon12to1", Types.VARCHAR },
			{ "mon1to2", Types.VARCHAR },
			{ "mon2to3", Types.VARCHAR },
			{ "mon3to4", Types.VARCHAR },
			{ "mon4to5", Types.VARCHAR },
			{ "tue8to9", Types.VARCHAR },
			{ "tue9to10", Types.VARCHAR },
			{ "tue10to11", Types.VARCHAR },
			{ "tue11to12", Types.VARCHAR },
			{ "tue12to1", Types.VARCHAR },
			{ "tue1to2", Types.VARCHAR },
			{ "tue2to3", Types.VARCHAR },
			{ "tue3to4", Types.VARCHAR },
			{ "tue4to5", Types.VARCHAR },
			{ "wed8to9", Types.VARCHAR },
			{ "wed9to10", Types.VARCHAR },
			{ "wed10to11", Types.VARCHAR },
			{ "wed11to12", Types.VARCHAR },
			{ "wed12to1", Types.VARCHAR },
			{ "wed1to2", Types.VARCHAR },
			{ "wed2to3", Types.VARCHAR },
			{ "wed3to4", Types.VARCHAR },
			{ "wed4to5", Types.VARCHAR },
			{ "thu8to9", Types.VARCHAR },
			{ "thu9to10", Types.VARCHAR },
			{ "thu10to11", Types.VARCHAR },
			{ "thu11to12", Types.VARCHAR },
			{ "thu12to1", Types.VARCHAR },
			{ "thu1to2", Types.VARCHAR },
			{ "thu2to3", Types.VARCHAR },
			{ "thu3to4", Types.VARCHAR },
			{ "thu4to5", Types.VARCHAR },
			{ "fri8to9", Types.VARCHAR },
			{ "fri9to10", Types.VARCHAR },
			{ "fri10to11", Types.VARCHAR },
			{ "fri11to12", Types.VARCHAR },
			{ "fri12to1", Types.VARCHAR },
			{ "fri1to2", Types.VARCHAR },
			{ "fri2to3", Types.VARCHAR },
			{ "fri3to4", Types.VARCHAR },
			{ "fri4to5", Types.VARCHAR },
			{ "sat8to9", Types.VARCHAR },
			{ "sat9to10", Types.VARCHAR },
			{ "sat10to11", Types.VARCHAR },
			{ "sat11to12", Types.VARCHAR },
			{ "sat12to1", Types.VARCHAR },
			{ "sat1to2", Types.VARCHAR },
			{ "sat2to3", Types.VARCHAR },
			{ "sat3to4", Types.VARCHAR },
			{ "sat4to5", Types.VARCHAR },
			{ "sun8to9", Types.VARCHAR },
			{ "sun9to10", Types.VARCHAR },
			{ "sun10to11", Types.VARCHAR },
			{ "sun11to12", Types.VARCHAR },
			{ "sun12to1", Types.VARCHAR },
			{ "sun1to2", Types.VARCHAR },
			{ "sun2to3", Types.VARCHAR },
			{ "sun3to4", Types.VARCHAR },
			{ "sun4to5", Types.VARCHAR },
			{ "author", Types.VARCHAR },
			{ "dateAdded", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table SAS_SASstudent (studentid LONG not null primary key,ASUId VARCHAR(75) null,mon8to9 VARCHAR(75) null,mon9to10 VARCHAR(75) null,mon10to11 VARCHAR(75) null,mon11to12 VARCHAR(75) null,mon12to1 VARCHAR(75) null,mon1to2 VARCHAR(75) null,mon2to3 VARCHAR(75) null,mon3to4 VARCHAR(75) null,mon4to5 VARCHAR(75) null,tue8to9 VARCHAR(75) null,tue9to10 VARCHAR(75) null,tue10to11 VARCHAR(75) null,tue11to12 VARCHAR(75) null,tue12to1 VARCHAR(75) null,tue1to2 VARCHAR(75) null,tue2to3 VARCHAR(75) null,tue3to4 VARCHAR(75) null,tue4to5 VARCHAR(75) null,wed8to9 VARCHAR(75) null,wed9to10 VARCHAR(75) null,wed10to11 VARCHAR(75) null,wed11to12 VARCHAR(75) null,wed12to1 VARCHAR(75) null,wed1to2 VARCHAR(75) null,wed2to3 VARCHAR(75) null,wed3to4 VARCHAR(75) null,wed4to5 VARCHAR(75) null,thu8to9 VARCHAR(75) null,thu9to10 VARCHAR(75) null,thu10to11 VARCHAR(75) null,thu11to12 VARCHAR(75) null,thu12to1 VARCHAR(75) null,thu1to2 VARCHAR(75) null,thu2to3 VARCHAR(75) null,thu3to4 VARCHAR(75) null,thu4to5 VARCHAR(75) null,fri8to9 VARCHAR(75) null,fri9to10 VARCHAR(75) null,fri10to11 VARCHAR(75) null,fri11to12 VARCHAR(75) null,fri12to1 VARCHAR(75) null,fri1to2 VARCHAR(75) null,fri2to3 VARCHAR(75) null,fri3to4 VARCHAR(75) null,fri4to5 VARCHAR(75) null,sat8to9 VARCHAR(75) null,sat9to10 VARCHAR(75) null,sat10to11 VARCHAR(75) null,sat11to12 VARCHAR(75) null,sat12to1 VARCHAR(75) null,sat1to2 VARCHAR(75) null,sat2to3 VARCHAR(75) null,sat3to4 VARCHAR(75) null,sat4to5 VARCHAR(75) null,sun8to9 VARCHAR(75) null,sun9to10 VARCHAR(75) null,sun10to11 VARCHAR(75) null,sun11to12 VARCHAR(75) null,sun12to1 VARCHAR(75) null,sun1to2 VARCHAR(75) null,sun2to3 VARCHAR(75) null,sun3to4 VARCHAR(75) null,sun4to5 VARCHAR(75) null,author VARCHAR(75) null,dateAdded DATE null)";
	public static final String TABLE_SQL_DROP = "drop table SAS_SASstudent";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.StudentAvailability.slayer.model.SASstudent"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.StudentAvailability.slayer.model.SASstudent"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.StudentAvailability.slayer.model.SASstudent"));

	public SASstudentModelImpl() {
	}

	public long getPrimaryKey() {
		return _studentid;
	}

	public void setPrimaryKey(long primaryKey) {
		setStudentid(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_studentid);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return SASstudent.class;
	}

	public String getModelClassName() {
		return SASstudent.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("studentid", getStudentid());
		attributes.put("ASUId", getASUId());
		attributes.put("mon8to9", getMon8to9());
		attributes.put("mon9to10", getMon9to10());
		attributes.put("mon10to11", getMon10to11());
		attributes.put("mon11to12", getMon11to12());
		attributes.put("mon12to1", getMon12to1());
		attributes.put("mon1to2", getMon1to2());
		attributes.put("mon2to3", getMon2to3());
		attributes.put("mon3to4", getMon3to4());
		attributes.put("mon4to5", getMon4to5());
		attributes.put("tue8to9", getTue8to9());
		attributes.put("tue9to10", getTue9to10());
		attributes.put("tue10to11", getTue10to11());
		attributes.put("tue11to12", getTue11to12());
		attributes.put("tue12to1", getTue12to1());
		attributes.put("tue1to2", getTue1to2());
		attributes.put("tue2to3", getTue2to3());
		attributes.put("tue3to4", getTue3to4());
		attributes.put("tue4to5", getTue4to5());
		attributes.put("wed8to9", getWed8to9());
		attributes.put("wed9to10", getWed9to10());
		attributes.put("wed10to11", getWed10to11());
		attributes.put("wed11to12", getWed11to12());
		attributes.put("wed12to1", getWed12to1());
		attributes.put("wed1to2", getWed1to2());
		attributes.put("wed2to3", getWed2to3());
		attributes.put("wed3to4", getWed3to4());
		attributes.put("wed4to5", getWed4to5());
		attributes.put("thu8to9", getThu8to9());
		attributes.put("thu9to10", getThu9to10());
		attributes.put("thu10to11", getThu10to11());
		attributes.put("thu11to12", getThu11to12());
		attributes.put("thu12to1", getThu12to1());
		attributes.put("thu1to2", getThu1to2());
		attributes.put("thu2to3", getThu2to3());
		attributes.put("thu3to4", getThu3to4());
		attributes.put("thu4to5", getThu4to5());
		attributes.put("fri8to9", getFri8to9());
		attributes.put("fri9to10", getFri9to10());
		attributes.put("fri10to11", getFri10to11());
		attributes.put("fri11to12", getFri11to12());
		attributes.put("fri12to1", getFri12to1());
		attributes.put("fri1to2", getFri1to2());
		attributes.put("fri2to3", getFri2to3());
		attributes.put("fri3to4", getFri3to4());
		attributes.put("fri4to5", getFri4to5());
		attributes.put("sat8to9", getSat8to9());
		attributes.put("sat9to10", getSat9to10());
		attributes.put("sat10to11", getSat10to11());
		attributes.put("sat11to12", getSat11to12());
		attributes.put("sat12to1", getSat12to1());
		attributes.put("sat1to2", getSat1to2());
		attributes.put("sat2to3", getSat2to3());
		attributes.put("sat3to4", getSat3to4());
		attributes.put("sat4to5", getSat4to5());
		attributes.put("sun8to9", getSun8to9());
		attributes.put("sun9to10", getSun9to10());
		attributes.put("sun10to11", getSun10to11());
		attributes.put("sun11to12", getSun11to12());
		attributes.put("sun12to1", getSun12to1());
		attributes.put("sun1to2", getSun1to2());
		attributes.put("sun2to3", getSun2to3());
		attributes.put("sun3to4", getSun3to4());
		attributes.put("sun4to5", getSun4to5());
		attributes.put("author", getAuthor());
		attributes.put("dateAdded", getDateAdded());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long studentid = (Long)attributes.get("studentid");

		if (studentid != null) {
			setStudentid(studentid);
		}

		String ASUId = (String)attributes.get("ASUId");

		if (ASUId != null) {
			setASUId(ASUId);
		}

		String mon8to9 = (String)attributes.get("mon8to9");

		if (mon8to9 != null) {
			setMon8to9(mon8to9);
		}

		String mon9to10 = (String)attributes.get("mon9to10");

		if (mon9to10 != null) {
			setMon9to10(mon9to10);
		}

		String mon10to11 = (String)attributes.get("mon10to11");

		if (mon10to11 != null) {
			setMon10to11(mon10to11);
		}

		String mon11to12 = (String)attributes.get("mon11to12");

		if (mon11to12 != null) {
			setMon11to12(mon11to12);
		}

		String mon12to1 = (String)attributes.get("mon12to1");

		if (mon12to1 != null) {
			setMon12to1(mon12to1);
		}

		String mon1to2 = (String)attributes.get("mon1to2");

		if (mon1to2 != null) {
			setMon1to2(mon1to2);
		}

		String mon2to3 = (String)attributes.get("mon2to3");

		if (mon2to3 != null) {
			setMon2to3(mon2to3);
		}

		String mon3to4 = (String)attributes.get("mon3to4");

		if (mon3to4 != null) {
			setMon3to4(mon3to4);
		}

		String mon4to5 = (String)attributes.get("mon4to5");

		if (mon4to5 != null) {
			setMon4to5(mon4to5);
		}

		String tue8to9 = (String)attributes.get("tue8to9");

		if (tue8to9 != null) {
			setTue8to9(tue8to9);
		}

		String tue9to10 = (String)attributes.get("tue9to10");

		if (tue9to10 != null) {
			setTue9to10(tue9to10);
		}

		String tue10to11 = (String)attributes.get("tue10to11");

		if (tue10to11 != null) {
			setTue10to11(tue10to11);
		}

		String tue11to12 = (String)attributes.get("tue11to12");

		if (tue11to12 != null) {
			setTue11to12(tue11to12);
		}

		String tue12to1 = (String)attributes.get("tue12to1");

		if (tue12to1 != null) {
			setTue12to1(tue12to1);
		}

		String tue1to2 = (String)attributes.get("tue1to2");

		if (tue1to2 != null) {
			setTue1to2(tue1to2);
		}

		String tue2to3 = (String)attributes.get("tue2to3");

		if (tue2to3 != null) {
			setTue2to3(tue2to3);
		}

		String tue3to4 = (String)attributes.get("tue3to4");

		if (tue3to4 != null) {
			setTue3to4(tue3to4);
		}

		String tue4to5 = (String)attributes.get("tue4to5");

		if (tue4to5 != null) {
			setTue4to5(tue4to5);
		}

		String wed8to9 = (String)attributes.get("wed8to9");

		if (wed8to9 != null) {
			setWed8to9(wed8to9);
		}

		String wed9to10 = (String)attributes.get("wed9to10");

		if (wed9to10 != null) {
			setWed9to10(wed9to10);
		}

		String wed10to11 = (String)attributes.get("wed10to11");

		if (wed10to11 != null) {
			setWed10to11(wed10to11);
		}

		String wed11to12 = (String)attributes.get("wed11to12");

		if (wed11to12 != null) {
			setWed11to12(wed11to12);
		}

		String wed12to1 = (String)attributes.get("wed12to1");

		if (wed12to1 != null) {
			setWed12to1(wed12to1);
		}

		String wed1to2 = (String)attributes.get("wed1to2");

		if (wed1to2 != null) {
			setWed1to2(wed1to2);
		}

		String wed2to3 = (String)attributes.get("wed2to3");

		if (wed2to3 != null) {
			setWed2to3(wed2to3);
		}

		String wed3to4 = (String)attributes.get("wed3to4");

		if (wed3to4 != null) {
			setWed3to4(wed3to4);
		}

		String wed4to5 = (String)attributes.get("wed4to5");

		if (wed4to5 != null) {
			setWed4to5(wed4to5);
		}

		String thu8to9 = (String)attributes.get("thu8to9");

		if (thu8to9 != null) {
			setThu8to9(thu8to9);
		}

		String thu9to10 = (String)attributes.get("thu9to10");

		if (thu9to10 != null) {
			setThu9to10(thu9to10);
		}

		String thu10to11 = (String)attributes.get("thu10to11");

		if (thu10to11 != null) {
			setThu10to11(thu10to11);
		}

		String thu11to12 = (String)attributes.get("thu11to12");

		if (thu11to12 != null) {
			setThu11to12(thu11to12);
		}

		String thu12to1 = (String)attributes.get("thu12to1");

		if (thu12to1 != null) {
			setThu12to1(thu12to1);
		}

		String thu1to2 = (String)attributes.get("thu1to2");

		if (thu1to2 != null) {
			setThu1to2(thu1to2);
		}

		String thu2to3 = (String)attributes.get("thu2to3");

		if (thu2to3 != null) {
			setThu2to3(thu2to3);
		}

		String thu3to4 = (String)attributes.get("thu3to4");

		if (thu3to4 != null) {
			setThu3to4(thu3to4);
		}

		String thu4to5 = (String)attributes.get("thu4to5");

		if (thu4to5 != null) {
			setThu4to5(thu4to5);
		}

		String fri8to9 = (String)attributes.get("fri8to9");

		if (fri8to9 != null) {
			setFri8to9(fri8to9);
		}

		String fri9to10 = (String)attributes.get("fri9to10");

		if (fri9to10 != null) {
			setFri9to10(fri9to10);
		}

		String fri10to11 = (String)attributes.get("fri10to11");

		if (fri10to11 != null) {
			setFri10to11(fri10to11);
		}

		String fri11to12 = (String)attributes.get("fri11to12");

		if (fri11to12 != null) {
			setFri11to12(fri11to12);
		}

		String fri12to1 = (String)attributes.get("fri12to1");

		if (fri12to1 != null) {
			setFri12to1(fri12to1);
		}

		String fri1to2 = (String)attributes.get("fri1to2");

		if (fri1to2 != null) {
			setFri1to2(fri1to2);
		}

		String fri2to3 = (String)attributes.get("fri2to3");

		if (fri2to3 != null) {
			setFri2to3(fri2to3);
		}

		String fri3to4 = (String)attributes.get("fri3to4");

		if (fri3to4 != null) {
			setFri3to4(fri3to4);
		}

		String fri4to5 = (String)attributes.get("fri4to5");

		if (fri4to5 != null) {
			setFri4to5(fri4to5);
		}

		String sat8to9 = (String)attributes.get("sat8to9");

		if (sat8to9 != null) {
			setSat8to9(sat8to9);
		}

		String sat9to10 = (String)attributes.get("sat9to10");

		if (sat9to10 != null) {
			setSat9to10(sat9to10);
		}

		String sat10to11 = (String)attributes.get("sat10to11");

		if (sat10to11 != null) {
			setSat10to11(sat10to11);
		}

		String sat11to12 = (String)attributes.get("sat11to12");

		if (sat11to12 != null) {
			setSat11to12(sat11to12);
		}

		String sat12to1 = (String)attributes.get("sat12to1");

		if (sat12to1 != null) {
			setSat12to1(sat12to1);
		}

		String sat1to2 = (String)attributes.get("sat1to2");

		if (sat1to2 != null) {
			setSat1to2(sat1to2);
		}

		String sat2to3 = (String)attributes.get("sat2to3");

		if (sat2to3 != null) {
			setSat2to3(sat2to3);
		}

		String sat3to4 = (String)attributes.get("sat3to4");

		if (sat3to4 != null) {
			setSat3to4(sat3to4);
		}

		String sat4to5 = (String)attributes.get("sat4to5");

		if (sat4to5 != null) {
			setSat4to5(sat4to5);
		}

		String sun8to9 = (String)attributes.get("sun8to9");

		if (sun8to9 != null) {
			setSun8to9(sun8to9);
		}

		String sun9to10 = (String)attributes.get("sun9to10");

		if (sun9to10 != null) {
			setSun9to10(sun9to10);
		}

		String sun10to11 = (String)attributes.get("sun10to11");

		if (sun10to11 != null) {
			setSun10to11(sun10to11);
		}

		String sun11to12 = (String)attributes.get("sun11to12");

		if (sun11to12 != null) {
			setSun11to12(sun11to12);
		}

		String sun12to1 = (String)attributes.get("sun12to1");

		if (sun12to1 != null) {
			setSun12to1(sun12to1);
		}

		String sun1to2 = (String)attributes.get("sun1to2");

		if (sun1to2 != null) {
			setSun1to2(sun1to2);
		}

		String sun2to3 = (String)attributes.get("sun2to3");

		if (sun2to3 != null) {
			setSun2to3(sun2to3);
		}

		String sun3to4 = (String)attributes.get("sun3to4");

		if (sun3to4 != null) {
			setSun3to4(sun3to4);
		}

		String sun4to5 = (String)attributes.get("sun4to5");

		if (sun4to5 != null) {
			setSun4to5(sun4to5);
		}

		String author = (String)attributes.get("author");

		if (author != null) {
			setAuthor(author);
		}

		Date dateAdded = (Date)attributes.get("dateAdded");

		if (dateAdded != null) {
			setDateAdded(dateAdded);
		}
	}

	public long getStudentid() {
		return _studentid;
	}

	public void setStudentid(long studentid) {
		_studentid = studentid;
	}

	public String getASUId() {
		if (_ASUId == null) {
			return StringPool.BLANK;
		}
		else {
			return _ASUId;
		}
	}

	public void setASUId(String ASUId) {
		_ASUId = ASUId;
	}

	public String getMon8to9() {
		if (_mon8to9 == null) {
			return StringPool.BLANK;
		}
		else {
			return _mon8to9;
		}
	}

	public void setMon8to9(String mon8to9) {
		_mon8to9 = mon8to9;
	}

	public String getMon9to10() {
		if (_mon9to10 == null) {
			return StringPool.BLANK;
		}
		else {
			return _mon9to10;
		}
	}

	public void setMon9to10(String mon9to10) {
		_mon9to10 = mon9to10;
	}

	public String getMon10to11() {
		if (_mon10to11 == null) {
			return StringPool.BLANK;
		}
		else {
			return _mon10to11;
		}
	}

	public void setMon10to11(String mon10to11) {
		_mon10to11 = mon10to11;
	}

	public String getMon11to12() {
		if (_mon11to12 == null) {
			return StringPool.BLANK;
		}
		else {
			return _mon11to12;
		}
	}

	public void setMon11to12(String mon11to12) {
		_mon11to12 = mon11to12;
	}

	public String getMon12to1() {
		if (_mon12to1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _mon12to1;
		}
	}

	public void setMon12to1(String mon12to1) {
		_mon12to1 = mon12to1;
	}

	public String getMon1to2() {
		if (_mon1to2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _mon1to2;
		}
	}

	public void setMon1to2(String mon1to2) {
		_mon1to2 = mon1to2;
	}

	public String getMon2to3() {
		if (_mon2to3 == null) {
			return StringPool.BLANK;
		}
		else {
			return _mon2to3;
		}
	}

	public void setMon2to3(String mon2to3) {
		_mon2to3 = mon2to3;
	}

	public String getMon3to4() {
		if (_mon3to4 == null) {
			return StringPool.BLANK;
		}
		else {
			return _mon3to4;
		}
	}

	public void setMon3to4(String mon3to4) {
		_mon3to4 = mon3to4;
	}

	public String getMon4to5() {
		if (_mon4to5 == null) {
			return StringPool.BLANK;
		}
		else {
			return _mon4to5;
		}
	}

	public void setMon4to5(String mon4to5) {
		_mon4to5 = mon4to5;
	}

	public String getTue8to9() {
		if (_tue8to9 == null) {
			return StringPool.BLANK;
		}
		else {
			return _tue8to9;
		}
	}

	public void setTue8to9(String tue8to9) {
		_tue8to9 = tue8to9;
	}

	public String getTue9to10() {
		if (_tue9to10 == null) {
			return StringPool.BLANK;
		}
		else {
			return _tue9to10;
		}
	}

	public void setTue9to10(String tue9to10) {
		_tue9to10 = tue9to10;
	}

	public String getTue10to11() {
		if (_tue10to11 == null) {
			return StringPool.BLANK;
		}
		else {
			return _tue10to11;
		}
	}

	public void setTue10to11(String tue10to11) {
		_tue10to11 = tue10to11;
	}

	public String getTue11to12() {
		if (_tue11to12 == null) {
			return StringPool.BLANK;
		}
		else {
			return _tue11to12;
		}
	}

	public void setTue11to12(String tue11to12) {
		_tue11to12 = tue11to12;
	}

	public String getTue12to1() {
		if (_tue12to1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _tue12to1;
		}
	}

	public void setTue12to1(String tue12to1) {
		_tue12to1 = tue12to1;
	}

	public String getTue1to2() {
		if (_tue1to2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _tue1to2;
		}
	}

	public void setTue1to2(String tue1to2) {
		_tue1to2 = tue1to2;
	}

	public String getTue2to3() {
		if (_tue2to3 == null) {
			return StringPool.BLANK;
		}
		else {
			return _tue2to3;
		}
	}

	public void setTue2to3(String tue2to3) {
		_tue2to3 = tue2to3;
	}

	public String getTue3to4() {
		if (_tue3to4 == null) {
			return StringPool.BLANK;
		}
		else {
			return _tue3to4;
		}
	}

	public void setTue3to4(String tue3to4) {
		_tue3to4 = tue3to4;
	}

	public String getTue4to5() {
		if (_tue4to5 == null) {
			return StringPool.BLANK;
		}
		else {
			return _tue4to5;
		}
	}

	public void setTue4to5(String tue4to5) {
		_tue4to5 = tue4to5;
	}

	public String getWed8to9() {
		if (_wed8to9 == null) {
			return StringPool.BLANK;
		}
		else {
			return _wed8to9;
		}
	}

	public void setWed8to9(String wed8to9) {
		_wed8to9 = wed8to9;
	}

	public String getWed9to10() {
		if (_wed9to10 == null) {
			return StringPool.BLANK;
		}
		else {
			return _wed9to10;
		}
	}

	public void setWed9to10(String wed9to10) {
		_wed9to10 = wed9to10;
	}

	public String getWed10to11() {
		if (_wed10to11 == null) {
			return StringPool.BLANK;
		}
		else {
			return _wed10to11;
		}
	}

	public void setWed10to11(String wed10to11) {
		_wed10to11 = wed10to11;
	}

	public String getWed11to12() {
		if (_wed11to12 == null) {
			return StringPool.BLANK;
		}
		else {
			return _wed11to12;
		}
	}

	public void setWed11to12(String wed11to12) {
		_wed11to12 = wed11to12;
	}

	public String getWed12to1() {
		if (_wed12to1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _wed12to1;
		}
	}

	public void setWed12to1(String wed12to1) {
		_wed12to1 = wed12to1;
	}

	public String getWed1to2() {
		if (_wed1to2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _wed1to2;
		}
	}

	public void setWed1to2(String wed1to2) {
		_wed1to2 = wed1to2;
	}

	public String getWed2to3() {
		if (_wed2to3 == null) {
			return StringPool.BLANK;
		}
		else {
			return _wed2to3;
		}
	}

	public void setWed2to3(String wed2to3) {
		_wed2to3 = wed2to3;
	}

	public String getWed3to4() {
		if (_wed3to4 == null) {
			return StringPool.BLANK;
		}
		else {
			return _wed3to4;
		}
	}

	public void setWed3to4(String wed3to4) {
		_wed3to4 = wed3to4;
	}

	public String getWed4to5() {
		if (_wed4to5 == null) {
			return StringPool.BLANK;
		}
		else {
			return _wed4to5;
		}
	}

	public void setWed4to5(String wed4to5) {
		_wed4to5 = wed4to5;
	}

	public String getThu8to9() {
		if (_thu8to9 == null) {
			return StringPool.BLANK;
		}
		else {
			return _thu8to9;
		}
	}

	public void setThu8to9(String thu8to9) {
		_thu8to9 = thu8to9;
	}

	public String getThu9to10() {
		if (_thu9to10 == null) {
			return StringPool.BLANK;
		}
		else {
			return _thu9to10;
		}
	}

	public void setThu9to10(String thu9to10) {
		_thu9to10 = thu9to10;
	}

	public String getThu10to11() {
		if (_thu10to11 == null) {
			return StringPool.BLANK;
		}
		else {
			return _thu10to11;
		}
	}

	public void setThu10to11(String thu10to11) {
		_thu10to11 = thu10to11;
	}

	public String getThu11to12() {
		if (_thu11to12 == null) {
			return StringPool.BLANK;
		}
		else {
			return _thu11to12;
		}
	}

	public void setThu11to12(String thu11to12) {
		_thu11to12 = thu11to12;
	}

	public String getThu12to1() {
		if (_thu12to1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _thu12to1;
		}
	}

	public void setThu12to1(String thu12to1) {
		_thu12to1 = thu12to1;
	}

	public String getThu1to2() {
		if (_thu1to2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _thu1to2;
		}
	}

	public void setThu1to2(String thu1to2) {
		_thu1to2 = thu1to2;
	}

	public String getThu2to3() {
		if (_thu2to3 == null) {
			return StringPool.BLANK;
		}
		else {
			return _thu2to3;
		}
	}

	public void setThu2to3(String thu2to3) {
		_thu2to3 = thu2to3;
	}

	public String getThu3to4() {
		if (_thu3to4 == null) {
			return StringPool.BLANK;
		}
		else {
			return _thu3to4;
		}
	}

	public void setThu3to4(String thu3to4) {
		_thu3to4 = thu3to4;
	}

	public String getThu4to5() {
		if (_thu4to5 == null) {
			return StringPool.BLANK;
		}
		else {
			return _thu4to5;
		}
	}

	public void setThu4to5(String thu4to5) {
		_thu4to5 = thu4to5;
	}

	public String getFri8to9() {
		if (_fri8to9 == null) {
			return StringPool.BLANK;
		}
		else {
			return _fri8to9;
		}
	}

	public void setFri8to9(String fri8to9) {
		_fri8to9 = fri8to9;
	}

	public String getFri9to10() {
		if (_fri9to10 == null) {
			return StringPool.BLANK;
		}
		else {
			return _fri9to10;
		}
	}

	public void setFri9to10(String fri9to10) {
		_fri9to10 = fri9to10;
	}

	public String getFri10to11() {
		if (_fri10to11 == null) {
			return StringPool.BLANK;
		}
		else {
			return _fri10to11;
		}
	}

	public void setFri10to11(String fri10to11) {
		_fri10to11 = fri10to11;
	}

	public String getFri11to12() {
		if (_fri11to12 == null) {
			return StringPool.BLANK;
		}
		else {
			return _fri11to12;
		}
	}

	public void setFri11to12(String fri11to12) {
		_fri11to12 = fri11to12;
	}

	public String getFri12to1() {
		if (_fri12to1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _fri12to1;
		}
	}

	public void setFri12to1(String fri12to1) {
		_fri12to1 = fri12to1;
	}

	public String getFri1to2() {
		if (_fri1to2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _fri1to2;
		}
	}

	public void setFri1to2(String fri1to2) {
		_fri1to2 = fri1to2;
	}

	public String getFri2to3() {
		if (_fri2to3 == null) {
			return StringPool.BLANK;
		}
		else {
			return _fri2to3;
		}
	}

	public void setFri2to3(String fri2to3) {
		_fri2to3 = fri2to3;
	}

	public String getFri3to4() {
		if (_fri3to4 == null) {
			return StringPool.BLANK;
		}
		else {
			return _fri3to4;
		}
	}

	public void setFri3to4(String fri3to4) {
		_fri3to4 = fri3to4;
	}

	public String getFri4to5() {
		if (_fri4to5 == null) {
			return StringPool.BLANK;
		}
		else {
			return _fri4to5;
		}
	}

	public void setFri4to5(String fri4to5) {
		_fri4to5 = fri4to5;
	}

	public String getSat8to9() {
		if (_sat8to9 == null) {
			return StringPool.BLANK;
		}
		else {
			return _sat8to9;
		}
	}

	public void setSat8to9(String sat8to9) {
		_sat8to9 = sat8to9;
	}

	public String getSat9to10() {
		if (_sat9to10 == null) {
			return StringPool.BLANK;
		}
		else {
			return _sat9to10;
		}
	}

	public void setSat9to10(String sat9to10) {
		_sat9to10 = sat9to10;
	}

	public String getSat10to11() {
		if (_sat10to11 == null) {
			return StringPool.BLANK;
		}
		else {
			return _sat10to11;
		}
	}

	public void setSat10to11(String sat10to11) {
		_sat10to11 = sat10to11;
	}

	public String getSat11to12() {
		if (_sat11to12 == null) {
			return StringPool.BLANK;
		}
		else {
			return _sat11to12;
		}
	}

	public void setSat11to12(String sat11to12) {
		_sat11to12 = sat11to12;
	}

	public String getSat12to1() {
		if (_sat12to1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _sat12to1;
		}
	}

	public void setSat12to1(String sat12to1) {
		_sat12to1 = sat12to1;
	}

	public String getSat1to2() {
		if (_sat1to2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _sat1to2;
		}
	}

	public void setSat1to2(String sat1to2) {
		_sat1to2 = sat1to2;
	}

	public String getSat2to3() {
		if (_sat2to3 == null) {
			return StringPool.BLANK;
		}
		else {
			return _sat2to3;
		}
	}

	public void setSat2to3(String sat2to3) {
		_sat2to3 = sat2to3;
	}

	public String getSat3to4() {
		if (_sat3to4 == null) {
			return StringPool.BLANK;
		}
		else {
			return _sat3to4;
		}
	}

	public void setSat3to4(String sat3to4) {
		_sat3to4 = sat3to4;
	}

	public String getSat4to5() {
		if (_sat4to5 == null) {
			return StringPool.BLANK;
		}
		else {
			return _sat4to5;
		}
	}

	public void setSat4to5(String sat4to5) {
		_sat4to5 = sat4to5;
	}

	public String getSun8to9() {
		if (_sun8to9 == null) {
			return StringPool.BLANK;
		}
		else {
			return _sun8to9;
		}
	}

	public void setSun8to9(String sun8to9) {
		_sun8to9 = sun8to9;
	}

	public String getSun9to10() {
		if (_sun9to10 == null) {
			return StringPool.BLANK;
		}
		else {
			return _sun9to10;
		}
	}

	public void setSun9to10(String sun9to10) {
		_sun9to10 = sun9to10;
	}

	public String getSun10to11() {
		if (_sun10to11 == null) {
			return StringPool.BLANK;
		}
		else {
			return _sun10to11;
		}
	}

	public void setSun10to11(String sun10to11) {
		_sun10to11 = sun10to11;
	}

	public String getSun11to12() {
		if (_sun11to12 == null) {
			return StringPool.BLANK;
		}
		else {
			return _sun11to12;
		}
	}

	public void setSun11to12(String sun11to12) {
		_sun11to12 = sun11to12;
	}

	public String getSun12to1() {
		if (_sun12to1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _sun12to1;
		}
	}

	public void setSun12to1(String sun12to1) {
		_sun12to1 = sun12to1;
	}

	public String getSun1to2() {
		if (_sun1to2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _sun1to2;
		}
	}

	public void setSun1to2(String sun1to2) {
		_sun1to2 = sun1to2;
	}

	public String getSun2to3() {
		if (_sun2to3 == null) {
			return StringPool.BLANK;
		}
		else {
			return _sun2to3;
		}
	}

	public void setSun2to3(String sun2to3) {
		_sun2to3 = sun2to3;
	}

	public String getSun3to4() {
		if (_sun3to4 == null) {
			return StringPool.BLANK;
		}
		else {
			return _sun3to4;
		}
	}

	public void setSun3to4(String sun3to4) {
		_sun3to4 = sun3to4;
	}

	public String getSun4to5() {
		if (_sun4to5 == null) {
			return StringPool.BLANK;
		}
		else {
			return _sun4to5;
		}
	}

	public void setSun4to5(String sun4to5) {
		_sun4to5 = sun4to5;
	}

	public String getAuthor() {
		if (_author == null) {
			return StringPool.BLANK;
		}
		else {
			return _author;
		}
	}

	public void setAuthor(String author) {
		_author = author;
	}

	public Date getDateAdded() {
		return _dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		_dateAdded = dateAdded;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			SASstudent.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SASstudent toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (SASstudent)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		SASstudentImpl saSstudentImpl = new SASstudentImpl();

		saSstudentImpl.setStudentid(getStudentid());
		saSstudentImpl.setASUId(getASUId());
		saSstudentImpl.setMon8to9(getMon8to9());
		saSstudentImpl.setMon9to10(getMon9to10());
		saSstudentImpl.setMon10to11(getMon10to11());
		saSstudentImpl.setMon11to12(getMon11to12());
		saSstudentImpl.setMon12to1(getMon12to1());
		saSstudentImpl.setMon1to2(getMon1to2());
		saSstudentImpl.setMon2to3(getMon2to3());
		saSstudentImpl.setMon3to4(getMon3to4());
		saSstudentImpl.setMon4to5(getMon4to5());
		saSstudentImpl.setTue8to9(getTue8to9());
		saSstudentImpl.setTue9to10(getTue9to10());
		saSstudentImpl.setTue10to11(getTue10to11());
		saSstudentImpl.setTue11to12(getTue11to12());
		saSstudentImpl.setTue12to1(getTue12to1());
		saSstudentImpl.setTue1to2(getTue1to2());
		saSstudentImpl.setTue2to3(getTue2to3());
		saSstudentImpl.setTue3to4(getTue3to4());
		saSstudentImpl.setTue4to5(getTue4to5());
		saSstudentImpl.setWed8to9(getWed8to9());
		saSstudentImpl.setWed9to10(getWed9to10());
		saSstudentImpl.setWed10to11(getWed10to11());
		saSstudentImpl.setWed11to12(getWed11to12());
		saSstudentImpl.setWed12to1(getWed12to1());
		saSstudentImpl.setWed1to2(getWed1to2());
		saSstudentImpl.setWed2to3(getWed2to3());
		saSstudentImpl.setWed3to4(getWed3to4());
		saSstudentImpl.setWed4to5(getWed4to5());
		saSstudentImpl.setThu8to9(getThu8to9());
		saSstudentImpl.setThu9to10(getThu9to10());
		saSstudentImpl.setThu10to11(getThu10to11());
		saSstudentImpl.setThu11to12(getThu11to12());
		saSstudentImpl.setThu12to1(getThu12to1());
		saSstudentImpl.setThu1to2(getThu1to2());
		saSstudentImpl.setThu2to3(getThu2to3());
		saSstudentImpl.setThu3to4(getThu3to4());
		saSstudentImpl.setThu4to5(getThu4to5());
		saSstudentImpl.setFri8to9(getFri8to9());
		saSstudentImpl.setFri9to10(getFri9to10());
		saSstudentImpl.setFri10to11(getFri10to11());
		saSstudentImpl.setFri11to12(getFri11to12());
		saSstudentImpl.setFri12to1(getFri12to1());
		saSstudentImpl.setFri1to2(getFri1to2());
		saSstudentImpl.setFri2to3(getFri2to3());
		saSstudentImpl.setFri3to4(getFri3to4());
		saSstudentImpl.setFri4to5(getFri4to5());
		saSstudentImpl.setSat8to9(getSat8to9());
		saSstudentImpl.setSat9to10(getSat9to10());
		saSstudentImpl.setSat10to11(getSat10to11());
		saSstudentImpl.setSat11to12(getSat11to12());
		saSstudentImpl.setSat12to1(getSat12to1());
		saSstudentImpl.setSat1to2(getSat1to2());
		saSstudentImpl.setSat2to3(getSat2to3());
		saSstudentImpl.setSat3to4(getSat3to4());
		saSstudentImpl.setSat4to5(getSat4to5());
		saSstudentImpl.setSun8to9(getSun8to9());
		saSstudentImpl.setSun9to10(getSun9to10());
		saSstudentImpl.setSun10to11(getSun10to11());
		saSstudentImpl.setSun11to12(getSun11to12());
		saSstudentImpl.setSun12to1(getSun12to1());
		saSstudentImpl.setSun1to2(getSun1to2());
		saSstudentImpl.setSun2to3(getSun2to3());
		saSstudentImpl.setSun3to4(getSun3to4());
		saSstudentImpl.setSun4to5(getSun4to5());
		saSstudentImpl.setAuthor(getAuthor());
		saSstudentImpl.setDateAdded(getDateAdded());

		saSstudentImpl.resetOriginalValues();

		return saSstudentImpl;
	}

	public int compareTo(SASstudent saSstudent) {
		long primaryKey = saSstudent.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		SASstudent saSstudent = null;

		try {
			saSstudent = (SASstudent)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = saSstudent.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<SASstudent> toCacheModel() {
		SASstudentCacheModel saSstudentCacheModel = new SASstudentCacheModel();

		saSstudentCacheModel.studentid = getStudentid();

		saSstudentCacheModel.ASUId = getASUId();

		String ASUId = saSstudentCacheModel.ASUId;

		if ((ASUId != null) && (ASUId.length() == 0)) {
			saSstudentCacheModel.ASUId = null;
		}

		saSstudentCacheModel.mon8to9 = getMon8to9();

		String mon8to9 = saSstudentCacheModel.mon8to9;

		if ((mon8to9 != null) && (mon8to9.length() == 0)) {
			saSstudentCacheModel.mon8to9 = null;
		}

		saSstudentCacheModel.mon9to10 = getMon9to10();

		String mon9to10 = saSstudentCacheModel.mon9to10;

		if ((mon9to10 != null) && (mon9to10.length() == 0)) {
			saSstudentCacheModel.mon9to10 = null;
		}

		saSstudentCacheModel.mon10to11 = getMon10to11();

		String mon10to11 = saSstudentCacheModel.mon10to11;

		if ((mon10to11 != null) && (mon10to11.length() == 0)) {
			saSstudentCacheModel.mon10to11 = null;
		}

		saSstudentCacheModel.mon11to12 = getMon11to12();

		String mon11to12 = saSstudentCacheModel.mon11to12;

		if ((mon11to12 != null) && (mon11to12.length() == 0)) {
			saSstudentCacheModel.mon11to12 = null;
		}

		saSstudentCacheModel.mon12to1 = getMon12to1();

		String mon12to1 = saSstudentCacheModel.mon12to1;

		if ((mon12to1 != null) && (mon12to1.length() == 0)) {
			saSstudentCacheModel.mon12to1 = null;
		}

		saSstudentCacheModel.mon1to2 = getMon1to2();

		String mon1to2 = saSstudentCacheModel.mon1to2;

		if ((mon1to2 != null) && (mon1to2.length() == 0)) {
			saSstudentCacheModel.mon1to2 = null;
		}

		saSstudentCacheModel.mon2to3 = getMon2to3();

		String mon2to3 = saSstudentCacheModel.mon2to3;

		if ((mon2to3 != null) && (mon2to3.length() == 0)) {
			saSstudentCacheModel.mon2to3 = null;
		}

		saSstudentCacheModel.mon3to4 = getMon3to4();

		String mon3to4 = saSstudentCacheModel.mon3to4;

		if ((mon3to4 != null) && (mon3to4.length() == 0)) {
			saSstudentCacheModel.mon3to4 = null;
		}

		saSstudentCacheModel.mon4to5 = getMon4to5();

		String mon4to5 = saSstudentCacheModel.mon4to5;

		if ((mon4to5 != null) && (mon4to5.length() == 0)) {
			saSstudentCacheModel.mon4to5 = null;
		}

		saSstudentCacheModel.tue8to9 = getTue8to9();

		String tue8to9 = saSstudentCacheModel.tue8to9;

		if ((tue8to9 != null) && (tue8to9.length() == 0)) {
			saSstudentCacheModel.tue8to9 = null;
		}

		saSstudentCacheModel.tue9to10 = getTue9to10();

		String tue9to10 = saSstudentCacheModel.tue9to10;

		if ((tue9to10 != null) && (tue9to10.length() == 0)) {
			saSstudentCacheModel.tue9to10 = null;
		}

		saSstudentCacheModel.tue10to11 = getTue10to11();

		String tue10to11 = saSstudentCacheModel.tue10to11;

		if ((tue10to11 != null) && (tue10to11.length() == 0)) {
			saSstudentCacheModel.tue10to11 = null;
		}

		saSstudentCacheModel.tue11to12 = getTue11to12();

		String tue11to12 = saSstudentCacheModel.tue11to12;

		if ((tue11to12 != null) && (tue11to12.length() == 0)) {
			saSstudentCacheModel.tue11to12 = null;
		}

		saSstudentCacheModel.tue12to1 = getTue12to1();

		String tue12to1 = saSstudentCacheModel.tue12to1;

		if ((tue12to1 != null) && (tue12to1.length() == 0)) {
			saSstudentCacheModel.tue12to1 = null;
		}

		saSstudentCacheModel.tue1to2 = getTue1to2();

		String tue1to2 = saSstudentCacheModel.tue1to2;

		if ((tue1to2 != null) && (tue1to2.length() == 0)) {
			saSstudentCacheModel.tue1to2 = null;
		}

		saSstudentCacheModel.tue2to3 = getTue2to3();

		String tue2to3 = saSstudentCacheModel.tue2to3;

		if ((tue2to3 != null) && (tue2to3.length() == 0)) {
			saSstudentCacheModel.tue2to3 = null;
		}

		saSstudentCacheModel.tue3to4 = getTue3to4();

		String tue3to4 = saSstudentCacheModel.tue3to4;

		if ((tue3to4 != null) && (tue3to4.length() == 0)) {
			saSstudentCacheModel.tue3to4 = null;
		}

		saSstudentCacheModel.tue4to5 = getTue4to5();

		String tue4to5 = saSstudentCacheModel.tue4to5;

		if ((tue4to5 != null) && (tue4to5.length() == 0)) {
			saSstudentCacheModel.tue4to5 = null;
		}

		saSstudentCacheModel.wed8to9 = getWed8to9();

		String wed8to9 = saSstudentCacheModel.wed8to9;

		if ((wed8to9 != null) && (wed8to9.length() == 0)) {
			saSstudentCacheModel.wed8to9 = null;
		}

		saSstudentCacheModel.wed9to10 = getWed9to10();

		String wed9to10 = saSstudentCacheModel.wed9to10;

		if ((wed9to10 != null) && (wed9to10.length() == 0)) {
			saSstudentCacheModel.wed9to10 = null;
		}

		saSstudentCacheModel.wed10to11 = getWed10to11();

		String wed10to11 = saSstudentCacheModel.wed10to11;

		if ((wed10to11 != null) && (wed10to11.length() == 0)) {
			saSstudentCacheModel.wed10to11 = null;
		}

		saSstudentCacheModel.wed11to12 = getWed11to12();

		String wed11to12 = saSstudentCacheModel.wed11to12;

		if ((wed11to12 != null) && (wed11to12.length() == 0)) {
			saSstudentCacheModel.wed11to12 = null;
		}

		saSstudentCacheModel.wed12to1 = getWed12to1();

		String wed12to1 = saSstudentCacheModel.wed12to1;

		if ((wed12to1 != null) && (wed12to1.length() == 0)) {
			saSstudentCacheModel.wed12to1 = null;
		}

		saSstudentCacheModel.wed1to2 = getWed1to2();

		String wed1to2 = saSstudentCacheModel.wed1to2;

		if ((wed1to2 != null) && (wed1to2.length() == 0)) {
			saSstudentCacheModel.wed1to2 = null;
		}

		saSstudentCacheModel.wed2to3 = getWed2to3();

		String wed2to3 = saSstudentCacheModel.wed2to3;

		if ((wed2to3 != null) && (wed2to3.length() == 0)) {
			saSstudentCacheModel.wed2to3 = null;
		}

		saSstudentCacheModel.wed3to4 = getWed3to4();

		String wed3to4 = saSstudentCacheModel.wed3to4;

		if ((wed3to4 != null) && (wed3to4.length() == 0)) {
			saSstudentCacheModel.wed3to4 = null;
		}

		saSstudentCacheModel.wed4to5 = getWed4to5();

		String wed4to5 = saSstudentCacheModel.wed4to5;

		if ((wed4to5 != null) && (wed4to5.length() == 0)) {
			saSstudentCacheModel.wed4to5 = null;
		}

		saSstudentCacheModel.thu8to9 = getThu8to9();

		String thu8to9 = saSstudentCacheModel.thu8to9;

		if ((thu8to9 != null) && (thu8to9.length() == 0)) {
			saSstudentCacheModel.thu8to9 = null;
		}

		saSstudentCacheModel.thu9to10 = getThu9to10();

		String thu9to10 = saSstudentCacheModel.thu9to10;

		if ((thu9to10 != null) && (thu9to10.length() == 0)) {
			saSstudentCacheModel.thu9to10 = null;
		}

		saSstudentCacheModel.thu10to11 = getThu10to11();

		String thu10to11 = saSstudentCacheModel.thu10to11;

		if ((thu10to11 != null) && (thu10to11.length() == 0)) {
			saSstudentCacheModel.thu10to11 = null;
		}

		saSstudentCacheModel.thu11to12 = getThu11to12();

		String thu11to12 = saSstudentCacheModel.thu11to12;

		if ((thu11to12 != null) && (thu11to12.length() == 0)) {
			saSstudentCacheModel.thu11to12 = null;
		}

		saSstudentCacheModel.thu12to1 = getThu12to1();

		String thu12to1 = saSstudentCacheModel.thu12to1;

		if ((thu12to1 != null) && (thu12to1.length() == 0)) {
			saSstudentCacheModel.thu12to1 = null;
		}

		saSstudentCacheModel.thu1to2 = getThu1to2();

		String thu1to2 = saSstudentCacheModel.thu1to2;

		if ((thu1to2 != null) && (thu1to2.length() == 0)) {
			saSstudentCacheModel.thu1to2 = null;
		}

		saSstudentCacheModel.thu2to3 = getThu2to3();

		String thu2to3 = saSstudentCacheModel.thu2to3;

		if ((thu2to3 != null) && (thu2to3.length() == 0)) {
			saSstudentCacheModel.thu2to3 = null;
		}

		saSstudentCacheModel.thu3to4 = getThu3to4();

		String thu3to4 = saSstudentCacheModel.thu3to4;

		if ((thu3to4 != null) && (thu3to4.length() == 0)) {
			saSstudentCacheModel.thu3to4 = null;
		}

		saSstudentCacheModel.thu4to5 = getThu4to5();

		String thu4to5 = saSstudentCacheModel.thu4to5;

		if ((thu4to5 != null) && (thu4to5.length() == 0)) {
			saSstudentCacheModel.thu4to5 = null;
		}

		saSstudentCacheModel.fri8to9 = getFri8to9();

		String fri8to9 = saSstudentCacheModel.fri8to9;

		if ((fri8to9 != null) && (fri8to9.length() == 0)) {
			saSstudentCacheModel.fri8to9 = null;
		}

		saSstudentCacheModel.fri9to10 = getFri9to10();

		String fri9to10 = saSstudentCacheModel.fri9to10;

		if ((fri9to10 != null) && (fri9to10.length() == 0)) {
			saSstudentCacheModel.fri9to10 = null;
		}

		saSstudentCacheModel.fri10to11 = getFri10to11();

		String fri10to11 = saSstudentCacheModel.fri10to11;

		if ((fri10to11 != null) && (fri10to11.length() == 0)) {
			saSstudentCacheModel.fri10to11 = null;
		}

		saSstudentCacheModel.fri11to12 = getFri11to12();

		String fri11to12 = saSstudentCacheModel.fri11to12;

		if ((fri11to12 != null) && (fri11to12.length() == 0)) {
			saSstudentCacheModel.fri11to12 = null;
		}

		saSstudentCacheModel.fri12to1 = getFri12to1();

		String fri12to1 = saSstudentCacheModel.fri12to1;

		if ((fri12to1 != null) && (fri12to1.length() == 0)) {
			saSstudentCacheModel.fri12to1 = null;
		}

		saSstudentCacheModel.fri1to2 = getFri1to2();

		String fri1to2 = saSstudentCacheModel.fri1to2;

		if ((fri1to2 != null) && (fri1to2.length() == 0)) {
			saSstudentCacheModel.fri1to2 = null;
		}

		saSstudentCacheModel.fri2to3 = getFri2to3();

		String fri2to3 = saSstudentCacheModel.fri2to3;

		if ((fri2to3 != null) && (fri2to3.length() == 0)) {
			saSstudentCacheModel.fri2to3 = null;
		}

		saSstudentCacheModel.fri3to4 = getFri3to4();

		String fri3to4 = saSstudentCacheModel.fri3to4;

		if ((fri3to4 != null) && (fri3to4.length() == 0)) {
			saSstudentCacheModel.fri3to4 = null;
		}

		saSstudentCacheModel.fri4to5 = getFri4to5();

		String fri4to5 = saSstudentCacheModel.fri4to5;

		if ((fri4to5 != null) && (fri4to5.length() == 0)) {
			saSstudentCacheModel.fri4to5 = null;
		}

		saSstudentCacheModel.sat8to9 = getSat8to9();

		String sat8to9 = saSstudentCacheModel.sat8to9;

		if ((sat8to9 != null) && (sat8to9.length() == 0)) {
			saSstudentCacheModel.sat8to9 = null;
		}

		saSstudentCacheModel.sat9to10 = getSat9to10();

		String sat9to10 = saSstudentCacheModel.sat9to10;

		if ((sat9to10 != null) && (sat9to10.length() == 0)) {
			saSstudentCacheModel.sat9to10 = null;
		}

		saSstudentCacheModel.sat10to11 = getSat10to11();

		String sat10to11 = saSstudentCacheModel.sat10to11;

		if ((sat10to11 != null) && (sat10to11.length() == 0)) {
			saSstudentCacheModel.sat10to11 = null;
		}

		saSstudentCacheModel.sat11to12 = getSat11to12();

		String sat11to12 = saSstudentCacheModel.sat11to12;

		if ((sat11to12 != null) && (sat11to12.length() == 0)) {
			saSstudentCacheModel.sat11to12 = null;
		}

		saSstudentCacheModel.sat12to1 = getSat12to1();

		String sat12to1 = saSstudentCacheModel.sat12to1;

		if ((sat12to1 != null) && (sat12to1.length() == 0)) {
			saSstudentCacheModel.sat12to1 = null;
		}

		saSstudentCacheModel.sat1to2 = getSat1to2();

		String sat1to2 = saSstudentCacheModel.sat1to2;

		if ((sat1to2 != null) && (sat1to2.length() == 0)) {
			saSstudentCacheModel.sat1to2 = null;
		}

		saSstudentCacheModel.sat2to3 = getSat2to3();

		String sat2to3 = saSstudentCacheModel.sat2to3;

		if ((sat2to3 != null) && (sat2to3.length() == 0)) {
			saSstudentCacheModel.sat2to3 = null;
		}

		saSstudentCacheModel.sat3to4 = getSat3to4();

		String sat3to4 = saSstudentCacheModel.sat3to4;

		if ((sat3to4 != null) && (sat3to4.length() == 0)) {
			saSstudentCacheModel.sat3to4 = null;
		}

		saSstudentCacheModel.sat4to5 = getSat4to5();

		String sat4to5 = saSstudentCacheModel.sat4to5;

		if ((sat4to5 != null) && (sat4to5.length() == 0)) {
			saSstudentCacheModel.sat4to5 = null;
		}

		saSstudentCacheModel.sun8to9 = getSun8to9();

		String sun8to9 = saSstudentCacheModel.sun8to9;

		if ((sun8to9 != null) && (sun8to9.length() == 0)) {
			saSstudentCacheModel.sun8to9 = null;
		}

		saSstudentCacheModel.sun9to10 = getSun9to10();

		String sun9to10 = saSstudentCacheModel.sun9to10;

		if ((sun9to10 != null) && (sun9to10.length() == 0)) {
			saSstudentCacheModel.sun9to10 = null;
		}

		saSstudentCacheModel.sun10to11 = getSun10to11();

		String sun10to11 = saSstudentCacheModel.sun10to11;

		if ((sun10to11 != null) && (sun10to11.length() == 0)) {
			saSstudentCacheModel.sun10to11 = null;
		}

		saSstudentCacheModel.sun11to12 = getSun11to12();

		String sun11to12 = saSstudentCacheModel.sun11to12;

		if ((sun11to12 != null) && (sun11to12.length() == 0)) {
			saSstudentCacheModel.sun11to12 = null;
		}

		saSstudentCacheModel.sun12to1 = getSun12to1();

		String sun12to1 = saSstudentCacheModel.sun12to1;

		if ((sun12to1 != null) && (sun12to1.length() == 0)) {
			saSstudentCacheModel.sun12to1 = null;
		}

		saSstudentCacheModel.sun1to2 = getSun1to2();

		String sun1to2 = saSstudentCacheModel.sun1to2;

		if ((sun1to2 != null) && (sun1to2.length() == 0)) {
			saSstudentCacheModel.sun1to2 = null;
		}

		saSstudentCacheModel.sun2to3 = getSun2to3();

		String sun2to3 = saSstudentCacheModel.sun2to3;

		if ((sun2to3 != null) && (sun2to3.length() == 0)) {
			saSstudentCacheModel.sun2to3 = null;
		}

		saSstudentCacheModel.sun3to4 = getSun3to4();

		String sun3to4 = saSstudentCacheModel.sun3to4;

		if ((sun3to4 != null) && (sun3to4.length() == 0)) {
			saSstudentCacheModel.sun3to4 = null;
		}

		saSstudentCacheModel.sun4to5 = getSun4to5();

		String sun4to5 = saSstudentCacheModel.sun4to5;

		if ((sun4to5 != null) && (sun4to5.length() == 0)) {
			saSstudentCacheModel.sun4to5 = null;
		}

		saSstudentCacheModel.author = getAuthor();

		String author = saSstudentCacheModel.author;

		if ((author != null) && (author.length() == 0)) {
			saSstudentCacheModel.author = null;
		}

		Date dateAdded = getDateAdded();

		if (dateAdded != null) {
			saSstudentCacheModel.dateAdded = dateAdded.getTime();
		}
		else {
			saSstudentCacheModel.dateAdded = Long.MIN_VALUE;
		}

		return saSstudentCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(135);

		sb.append("{studentid=");
		sb.append(getStudentid());
		sb.append(", ASUId=");
		sb.append(getASUId());
		sb.append(", mon8to9=");
		sb.append(getMon8to9());
		sb.append(", mon9to10=");
		sb.append(getMon9to10());
		sb.append(", mon10to11=");
		sb.append(getMon10to11());
		sb.append(", mon11to12=");
		sb.append(getMon11to12());
		sb.append(", mon12to1=");
		sb.append(getMon12to1());
		sb.append(", mon1to2=");
		sb.append(getMon1to2());
		sb.append(", mon2to3=");
		sb.append(getMon2to3());
		sb.append(", mon3to4=");
		sb.append(getMon3to4());
		sb.append(", mon4to5=");
		sb.append(getMon4to5());
		sb.append(", tue8to9=");
		sb.append(getTue8to9());
		sb.append(", tue9to10=");
		sb.append(getTue9to10());
		sb.append(", tue10to11=");
		sb.append(getTue10to11());
		sb.append(", tue11to12=");
		sb.append(getTue11to12());
		sb.append(", tue12to1=");
		sb.append(getTue12to1());
		sb.append(", tue1to2=");
		sb.append(getTue1to2());
		sb.append(", tue2to3=");
		sb.append(getTue2to3());
		sb.append(", tue3to4=");
		sb.append(getTue3to4());
		sb.append(", tue4to5=");
		sb.append(getTue4to5());
		sb.append(", wed8to9=");
		sb.append(getWed8to9());
		sb.append(", wed9to10=");
		sb.append(getWed9to10());
		sb.append(", wed10to11=");
		sb.append(getWed10to11());
		sb.append(", wed11to12=");
		sb.append(getWed11to12());
		sb.append(", wed12to1=");
		sb.append(getWed12to1());
		sb.append(", wed1to2=");
		sb.append(getWed1to2());
		sb.append(", wed2to3=");
		sb.append(getWed2to3());
		sb.append(", wed3to4=");
		sb.append(getWed3to4());
		sb.append(", wed4to5=");
		sb.append(getWed4to5());
		sb.append(", thu8to9=");
		sb.append(getThu8to9());
		sb.append(", thu9to10=");
		sb.append(getThu9to10());
		sb.append(", thu10to11=");
		sb.append(getThu10to11());
		sb.append(", thu11to12=");
		sb.append(getThu11to12());
		sb.append(", thu12to1=");
		sb.append(getThu12to1());
		sb.append(", thu1to2=");
		sb.append(getThu1to2());
		sb.append(", thu2to3=");
		sb.append(getThu2to3());
		sb.append(", thu3to4=");
		sb.append(getThu3to4());
		sb.append(", thu4to5=");
		sb.append(getThu4to5());
		sb.append(", fri8to9=");
		sb.append(getFri8to9());
		sb.append(", fri9to10=");
		sb.append(getFri9to10());
		sb.append(", fri10to11=");
		sb.append(getFri10to11());
		sb.append(", fri11to12=");
		sb.append(getFri11to12());
		sb.append(", fri12to1=");
		sb.append(getFri12to1());
		sb.append(", fri1to2=");
		sb.append(getFri1to2());
		sb.append(", fri2to3=");
		sb.append(getFri2to3());
		sb.append(", fri3to4=");
		sb.append(getFri3to4());
		sb.append(", fri4to5=");
		sb.append(getFri4to5());
		sb.append(", sat8to9=");
		sb.append(getSat8to9());
		sb.append(", sat9to10=");
		sb.append(getSat9to10());
		sb.append(", sat10to11=");
		sb.append(getSat10to11());
		sb.append(", sat11to12=");
		sb.append(getSat11to12());
		sb.append(", sat12to1=");
		sb.append(getSat12to1());
		sb.append(", sat1to2=");
		sb.append(getSat1to2());
		sb.append(", sat2to3=");
		sb.append(getSat2to3());
		sb.append(", sat3to4=");
		sb.append(getSat3to4());
		sb.append(", sat4to5=");
		sb.append(getSat4to5());
		sb.append(", sun8to9=");
		sb.append(getSun8to9());
		sb.append(", sun9to10=");
		sb.append(getSun9to10());
		sb.append(", sun10to11=");
		sb.append(getSun10to11());
		sb.append(", sun11to12=");
		sb.append(getSun11to12());
		sb.append(", sun12to1=");
		sb.append(getSun12to1());
		sb.append(", sun1to2=");
		sb.append(getSun1to2());
		sb.append(", sun2to3=");
		sb.append(getSun2to3());
		sb.append(", sun3to4=");
		sb.append(getSun3to4());
		sb.append(", sun4to5=");
		sb.append(getSun4to5());
		sb.append(", author=");
		sb.append(getAuthor());
		sb.append(", dateAdded=");
		sb.append(getDateAdded());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(205);

		sb.append("<model><model-name>");
		sb.append("com.StudentAvailability.slayer.model.SASstudent");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>studentid</column-name><column-value><![CDATA[");
		sb.append(getStudentid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ASUId</column-name><column-value><![CDATA[");
		sb.append(getASUId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mon8to9</column-name><column-value><![CDATA[");
		sb.append(getMon8to9());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mon9to10</column-name><column-value><![CDATA[");
		sb.append(getMon9to10());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mon10to11</column-name><column-value><![CDATA[");
		sb.append(getMon10to11());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mon11to12</column-name><column-value><![CDATA[");
		sb.append(getMon11to12());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mon12to1</column-name><column-value><![CDATA[");
		sb.append(getMon12to1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mon1to2</column-name><column-value><![CDATA[");
		sb.append(getMon1to2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mon2to3</column-name><column-value><![CDATA[");
		sb.append(getMon2to3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mon3to4</column-name><column-value><![CDATA[");
		sb.append(getMon3to4());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mon4to5</column-name><column-value><![CDATA[");
		sb.append(getMon4to5());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tue8to9</column-name><column-value><![CDATA[");
		sb.append(getTue8to9());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tue9to10</column-name><column-value><![CDATA[");
		sb.append(getTue9to10());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tue10to11</column-name><column-value><![CDATA[");
		sb.append(getTue10to11());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tue11to12</column-name><column-value><![CDATA[");
		sb.append(getTue11to12());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tue12to1</column-name><column-value><![CDATA[");
		sb.append(getTue12to1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tue1to2</column-name><column-value><![CDATA[");
		sb.append(getTue1to2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tue2to3</column-name><column-value><![CDATA[");
		sb.append(getTue2to3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tue3to4</column-name><column-value><![CDATA[");
		sb.append(getTue3to4());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tue4to5</column-name><column-value><![CDATA[");
		sb.append(getTue4to5());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>wed8to9</column-name><column-value><![CDATA[");
		sb.append(getWed8to9());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>wed9to10</column-name><column-value><![CDATA[");
		sb.append(getWed9to10());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>wed10to11</column-name><column-value><![CDATA[");
		sb.append(getWed10to11());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>wed11to12</column-name><column-value><![CDATA[");
		sb.append(getWed11to12());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>wed12to1</column-name><column-value><![CDATA[");
		sb.append(getWed12to1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>wed1to2</column-name><column-value><![CDATA[");
		sb.append(getWed1to2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>wed2to3</column-name><column-value><![CDATA[");
		sb.append(getWed2to3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>wed3to4</column-name><column-value><![CDATA[");
		sb.append(getWed3to4());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>wed4to5</column-name><column-value><![CDATA[");
		sb.append(getWed4to5());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thu8to9</column-name><column-value><![CDATA[");
		sb.append(getThu8to9());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thu9to10</column-name><column-value><![CDATA[");
		sb.append(getThu9to10());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thu10to11</column-name><column-value><![CDATA[");
		sb.append(getThu10to11());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thu11to12</column-name><column-value><![CDATA[");
		sb.append(getThu11to12());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thu12to1</column-name><column-value><![CDATA[");
		sb.append(getThu12to1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thu1to2</column-name><column-value><![CDATA[");
		sb.append(getThu1to2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thu2to3</column-name><column-value><![CDATA[");
		sb.append(getThu2to3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thu3to4</column-name><column-value><![CDATA[");
		sb.append(getThu3to4());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>thu4to5</column-name><column-value><![CDATA[");
		sb.append(getThu4to5());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fri8to9</column-name><column-value><![CDATA[");
		sb.append(getFri8to9());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fri9to10</column-name><column-value><![CDATA[");
		sb.append(getFri9to10());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fri10to11</column-name><column-value><![CDATA[");
		sb.append(getFri10to11());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fri11to12</column-name><column-value><![CDATA[");
		sb.append(getFri11to12());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fri12to1</column-name><column-value><![CDATA[");
		sb.append(getFri12to1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fri1to2</column-name><column-value><![CDATA[");
		sb.append(getFri1to2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fri2to3</column-name><column-value><![CDATA[");
		sb.append(getFri2to3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fri3to4</column-name><column-value><![CDATA[");
		sb.append(getFri3to4());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fri4to5</column-name><column-value><![CDATA[");
		sb.append(getFri4to5());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sat8to9</column-name><column-value><![CDATA[");
		sb.append(getSat8to9());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sat9to10</column-name><column-value><![CDATA[");
		sb.append(getSat9to10());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sat10to11</column-name><column-value><![CDATA[");
		sb.append(getSat10to11());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sat11to12</column-name><column-value><![CDATA[");
		sb.append(getSat11to12());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sat12to1</column-name><column-value><![CDATA[");
		sb.append(getSat12to1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sat1to2</column-name><column-value><![CDATA[");
		sb.append(getSat1to2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sat2to3</column-name><column-value><![CDATA[");
		sb.append(getSat2to3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sat3to4</column-name><column-value><![CDATA[");
		sb.append(getSat3to4());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sat4to5</column-name><column-value><![CDATA[");
		sb.append(getSat4to5());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sun8to9</column-name><column-value><![CDATA[");
		sb.append(getSun8to9());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sun9to10</column-name><column-value><![CDATA[");
		sb.append(getSun9to10());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sun10to11</column-name><column-value><![CDATA[");
		sb.append(getSun10to11());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sun11to12</column-name><column-value><![CDATA[");
		sb.append(getSun11to12());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sun12to1</column-name><column-value><![CDATA[");
		sb.append(getSun12to1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sun1to2</column-name><column-value><![CDATA[");
		sb.append(getSun1to2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sun2to3</column-name><column-value><![CDATA[");
		sb.append(getSun2to3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sun3to4</column-name><column-value><![CDATA[");
		sb.append(getSun3to4());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>sun4to5</column-name><column-value><![CDATA[");
		sb.append(getSun4to5());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>author</column-name><column-value><![CDATA[");
		sb.append(getAuthor());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dateAdded</column-name><column-value><![CDATA[");
		sb.append(getDateAdded());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = SASstudent.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			SASstudent.class
		};
	private long _studentid;
	private String _ASUId;
	private String _mon8to9;
	private String _mon9to10;
	private String _mon10to11;
	private String _mon11to12;
	private String _mon12to1;
	private String _mon1to2;
	private String _mon2to3;
	private String _mon3to4;
	private String _mon4to5;
	private String _tue8to9;
	private String _tue9to10;
	private String _tue10to11;
	private String _tue11to12;
	private String _tue12to1;
	private String _tue1to2;
	private String _tue2to3;
	private String _tue3to4;
	private String _tue4to5;
	private String _wed8to9;
	private String _wed9to10;
	private String _wed10to11;
	private String _wed11to12;
	private String _wed12to1;
	private String _wed1to2;
	private String _wed2to3;
	private String _wed3to4;
	private String _wed4to5;
	private String _thu8to9;
	private String _thu9to10;
	private String _thu10to11;
	private String _thu11to12;
	private String _thu12to1;
	private String _thu1to2;
	private String _thu2to3;
	private String _thu3to4;
	private String _thu4to5;
	private String _fri8to9;
	private String _fri9to10;
	private String _fri10to11;
	private String _fri11to12;
	private String _fri12to1;
	private String _fri1to2;
	private String _fri2to3;
	private String _fri3to4;
	private String _fri4to5;
	private String _sat8to9;
	private String _sat9to10;
	private String _sat10to11;
	private String _sat11to12;
	private String _sat12to1;
	private String _sat1to2;
	private String _sat2to3;
	private String _sat3to4;
	private String _sat4to5;
	private String _sun8to9;
	private String _sun9to10;
	private String _sun10to11;
	private String _sun11to12;
	private String _sun12to1;
	private String _sun1to2;
	private String _sun2to3;
	private String _sun3to4;
	private String _sun4to5;
	private String _author;
	private Date _dateAdded;
	private SASstudent _escapedModelProxy;
}