/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.CreateUser.service.base;

import com.CreateUser.model.useraccount;

import com.CreateUser.service.persistence.useraccountPersistence;
import com.CreateUser.service.useraccountLocalService;
import com.CreateUser.service.useraccountService;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the useraccount local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.CreateUser.service.impl.useraccountLocalServiceImpl}.
 * </p>
 *
 * @author Shruthi
 * @see com.CreateUser.service.impl.useraccountLocalServiceImpl
 * @see com.CreateUser.service.useraccountLocalServiceUtil
 * @generated
 */
public abstract class useraccountLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements useraccountLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.CreateUser.service.useraccountLocalServiceUtil} to access the useraccount local service.
	 */

	/**
	 * Adds the useraccount to the database. Also notifies the appropriate model listeners.
	 *
	 * @param useraccount the useraccount
	 * @return the useraccount that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public useraccount adduseraccount(useraccount useraccount)
		throws SystemException {
		useraccount.setNew(true);

		return useraccountPersistence.update(useraccount, false);
	}

	/**
	 * Creates a new useraccount with the primary key. Does not add the useraccount to the database.
	 *
	 * @param useraccountId the primary key for the new useraccount
	 * @return the new useraccount
	 */
	public useraccount createuseraccount(long useraccountId) {
		return useraccountPersistence.create(useraccountId);
	}

	/**
	 * Deletes the useraccount with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param useraccountId the primary key of the useraccount
	 * @return the useraccount that was removed
	 * @throws PortalException if a useraccount with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public useraccount deleteuseraccount(long useraccountId)
		throws PortalException, SystemException {
		return useraccountPersistence.remove(useraccountId);
	}

	/**
	 * Deletes the useraccount from the database. Also notifies the appropriate model listeners.
	 *
	 * @param useraccount the useraccount
	 * @return the useraccount that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public useraccount deleteuseraccount(useraccount useraccount)
		throws SystemException {
		return useraccountPersistence.remove(useraccount);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(useraccount.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return useraccountPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return useraccountPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return useraccountPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return useraccountPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public useraccount fetchuseraccount(long useraccountId)
		throws SystemException {
		return useraccountPersistence.fetchByPrimaryKey(useraccountId);
	}

	/**
	 * Returns the useraccount with the primary key.
	 *
	 * @param useraccountId the primary key of the useraccount
	 * @return the useraccount
	 * @throws PortalException if a useraccount with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public useraccount getuseraccount(long useraccountId)
		throws PortalException, SystemException {
		return useraccountPersistence.findByPrimaryKey(useraccountId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return useraccountPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the useraccounts.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of useraccounts
	 * @param end the upper bound of the range of useraccounts (not inclusive)
	 * @return the range of useraccounts
	 * @throws SystemException if a system exception occurred
	 */
	public List<useraccount> getuseraccounts(int start, int end)
		throws SystemException {
		return useraccountPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of useraccounts.
	 *
	 * @return the number of useraccounts
	 * @throws SystemException if a system exception occurred
	 */
	public int getuseraccountsCount() throws SystemException {
		return useraccountPersistence.countAll();
	}

	/**
	 * Updates the useraccount in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param useraccount the useraccount
	 * @return the useraccount that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public useraccount updateuseraccount(useraccount useraccount)
		throws SystemException {
		return updateuseraccount(useraccount, true);
	}

	/**
	 * Updates the useraccount in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param useraccount the useraccount
	 * @param merge whether to merge the useraccount with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the useraccount that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public useraccount updateuseraccount(useraccount useraccount, boolean merge)
		throws SystemException {
		useraccount.setNew(false);

		return useraccountPersistence.update(useraccount, merge);
	}

	/**
	 * Returns the useraccount local service.
	 *
	 * @return the useraccount local service
	 */
	public useraccountLocalService getuseraccountLocalService() {
		return useraccountLocalService;
	}

	/**
	 * Sets the useraccount local service.
	 *
	 * @param useraccountLocalService the useraccount local service
	 */
	public void setuseraccountLocalService(
		useraccountLocalService useraccountLocalService) {
		this.useraccountLocalService = useraccountLocalService;
	}

	/**
	 * Returns the useraccount remote service.
	 *
	 * @return the useraccount remote service
	 */
	public useraccountService getuseraccountService() {
		return useraccountService;
	}

	/**
	 * Sets the useraccount remote service.
	 *
	 * @param useraccountService the useraccount remote service
	 */
	public void setuseraccountService(useraccountService useraccountService) {
		this.useraccountService = useraccountService;
	}

	/**
	 * Returns the useraccount persistence.
	 *
	 * @return the useraccount persistence
	 */
	public useraccountPersistence getuseraccountPersistence() {
		return useraccountPersistence;
	}

	/**
	 * Sets the useraccount persistence.
	 *
	 * @param useraccountPersistence the useraccount persistence
	 */
	public void setuseraccountPersistence(
		useraccountPersistence useraccountPersistence) {
		this.useraccountPersistence = useraccountPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.CreateUser.model.useraccount",
			useraccountLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.CreateUser.model.useraccount");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return useraccount.class;
	}

	protected String getModelClassName() {
		return useraccount.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = useraccountPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = useraccountLocalService.class)
	protected useraccountLocalService useraccountLocalService;
	@BeanReference(type = useraccountService.class)
	protected useraccountService useraccountService;
	@BeanReference(type = useraccountPersistence.class)
	protected useraccountPersistence useraccountPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private useraccountLocalServiceClpInvoker _clpInvoker = new useraccountLocalServiceClpInvoker();
}