/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.StudentAvailability.slayer.service.base;

import com.StudentAvailability.slayer.model.SASstudent;
import com.StudentAvailability.slayer.service.SASstudentLocalService;
import com.StudentAvailability.slayer.service.persistence.SASstudentPersistence;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the s a sstudent local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.StudentAvailability.slayer.service.impl.SASstudentLocalServiceImpl}.
 * </p>
 *
 * @author Purva
 * @see com.StudentAvailability.slayer.service.impl.SASstudentLocalServiceImpl
 * @see com.StudentAvailability.slayer.service.SASstudentLocalServiceUtil
 * @generated
 */
public abstract class SASstudentLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements SASstudentLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.StudentAvailability.slayer.service.SASstudentLocalServiceUtil} to access the s a sstudent local service.
	 */

	/**
	 * Adds the s a sstudent to the database. Also notifies the appropriate model listeners.
	 *
	 * @param saSstudent the s a sstudent
	 * @return the s a sstudent that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public SASstudent addSASstudent(SASstudent saSstudent)
		throws SystemException {
		saSstudent.setNew(true);

		return saSstudentPersistence.update(saSstudent, false);
	}

	/**
	 * Creates a new s a sstudent with the primary key. Does not add the s a sstudent to the database.
	 *
	 * @param studentid the primary key for the new s a sstudent
	 * @return the new s a sstudent
	 */
	public SASstudent createSASstudent(long studentid) {
		return saSstudentPersistence.create(studentid);
	}

	/**
	 * Deletes the s a sstudent with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param studentid the primary key of the s a sstudent
	 * @return the s a sstudent that was removed
	 * @throws PortalException if a s a sstudent with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public SASstudent deleteSASstudent(long studentid)
		throws PortalException, SystemException {
		return saSstudentPersistence.remove(studentid);
	}

	/**
	 * Deletes the s a sstudent from the database. Also notifies the appropriate model listeners.
	 *
	 * @param saSstudent the s a sstudent
	 * @return the s a sstudent that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public SASstudent deleteSASstudent(SASstudent saSstudent)
		throws SystemException {
		return saSstudentPersistence.remove(saSstudent);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(SASstudent.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return saSstudentPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return saSstudentPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return saSstudentPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return saSstudentPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public SASstudent fetchSASstudent(long studentid) throws SystemException {
		return saSstudentPersistence.fetchByPrimaryKey(studentid);
	}

	/**
	 * Returns the s a sstudent with the primary key.
	 *
	 * @param studentid the primary key of the s a sstudent
	 * @return the s a sstudent
	 * @throws PortalException if a s a sstudent with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public SASstudent getSASstudent(long studentid)
		throws PortalException, SystemException {
		return saSstudentPersistence.findByPrimaryKey(studentid);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return saSstudentPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the s a sstudents.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of s a sstudents
	 * @param end the upper bound of the range of s a sstudents (not inclusive)
	 * @return the range of s a sstudents
	 * @throws SystemException if a system exception occurred
	 */
	public List<SASstudent> getSASstudents(int start, int end)
		throws SystemException {
		return saSstudentPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of s a sstudents.
	 *
	 * @return the number of s a sstudents
	 * @throws SystemException if a system exception occurred
	 */
	public int getSASstudentsCount() throws SystemException {
		return saSstudentPersistence.countAll();
	}

	/**
	 * Updates the s a sstudent in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param saSstudent the s a sstudent
	 * @return the s a sstudent that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public SASstudent updateSASstudent(SASstudent saSstudent)
		throws SystemException {
		return updateSASstudent(saSstudent, true);
	}

	/**
	 * Updates the s a sstudent in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param saSstudent the s a sstudent
	 * @param merge whether to merge the s a sstudent with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the s a sstudent that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public SASstudent updateSASstudent(SASstudent saSstudent, boolean merge)
		throws SystemException {
		saSstudent.setNew(false);

		return saSstudentPersistence.update(saSstudent, merge);
	}

	/**
	 * Returns the s a sstudent local service.
	 *
	 * @return the s a sstudent local service
	 */
	public SASstudentLocalService getSASstudentLocalService() {
		return saSstudentLocalService;
	}

	/**
	 * Sets the s a sstudent local service.
	 *
	 * @param saSstudentLocalService the s a sstudent local service
	 */
	public void setSASstudentLocalService(
		SASstudentLocalService saSstudentLocalService) {
		this.saSstudentLocalService = saSstudentLocalService;
	}

	/**
	 * Returns the s a sstudent persistence.
	 *
	 * @return the s a sstudent persistence
	 */
	public SASstudentPersistence getSASstudentPersistence() {
		return saSstudentPersistence;
	}

	/**
	 * Sets the s a sstudent persistence.
	 *
	 * @param saSstudentPersistence the s a sstudent persistence
	 */
	public void setSASstudentPersistence(
		SASstudentPersistence saSstudentPersistence) {
		this.saSstudentPersistence = saSstudentPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.StudentAvailability.slayer.model.SASstudent",
			saSstudentLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.StudentAvailability.slayer.model.SASstudent");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return SASstudent.class;
	}

	protected String getModelClassName() {
		return SASstudent.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = saSstudentPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = SASstudentLocalService.class)
	protected SASstudentLocalService saSstudentLocalService;
	@BeanReference(type = SASstudentPersistence.class)
	protected SASstudentPersistence saSstudentPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private SASstudentLocalServiceClpInvoker _clpInvoker = new SASstudentLocalServiceClpInvoker();
}