/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.asu.poly.iProjects.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the iProject service. Represents a row in the &quot;poly_iProject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.asu.poly.iProjects.model.impl.iProjectModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.asu.poly.iProjects.model.impl.iProjectImpl}.
 * </p>
 *
 * @author Shruthi
 * @see iProject
 * @see com.asu.poly.iProjects.model.impl.iProjectImpl
 * @see com.asu.poly.iProjects.model.impl.iProjectModelImpl
 * @generated
 */
public interface iProjectModel extends BaseModel<iProject> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a i project model instance should use the {@link iProject} interface instead.
	 */

	/**
	 * Returns the primary key of this i project.
	 *
	 * @return the primary key of this i project
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this i project.
	 *
	 * @param primaryKey the primary key of this i project
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the project i d of this i project.
	 *
	 * @return the project i d of this i project
	 */
	public long getProjectID();

	/**
	 * Sets the project i d of this i project.
	 *
	 * @param projectID the project i d of this i project
	 */
	public void setProjectID(long projectID);

	/**
	 * Returns the project title of this i project.
	 *
	 * @return the project title of this i project
	 */
	@AutoEscape
	public String getProjectTitle();

	/**
	 * Sets the project title of this i project.
	 *
	 * @param projectTitle the project title of this i project
	 */
	public void setProjectTitle(String projectTitle);

	/**
	 * Returns the projectdescription of this i project.
	 *
	 * @return the projectdescription of this i project
	 */
	@AutoEscape
	public String getProjectdescription();

	/**
	 * Sets the projectdescription of this i project.
	 *
	 * @param projectdescription the projectdescription of this i project
	 */
	public void setProjectdescription(String projectdescription);

	/**
	 * Returns the sponsor of this i project.
	 *
	 * @return the sponsor of this i project
	 */
	@AutoEscape
	public String getSponsor();

	/**
	 * Sets the sponsor of this i project.
	 *
	 * @param sponsor the sponsor of this i project
	 */
	public void setSponsor(String sponsor);

	/**
	 * Returns the required skills of this i project.
	 *
	 * @return the required skills of this i project
	 */
	@AutoEscape
	public String getRequiredSkills();

	/**
	 * Sets the required skills of this i project.
	 *
	 * @param requiredSkills the required skills of this i project
	 */
	public void setRequiredSkills(String requiredSkills);

	/**
	 * Returns the contact of this i project.
	 *
	 * @return the contact of this i project
	 */
	@AutoEscape
	public String getContact();

	/**
	 * Sets the contact of this i project.
	 *
	 * @param contact the contact of this i project
	 */
	public void setContact(String contact);

	/**
	 * Returns the status of this i project.
	 *
	 * @return the status of this i project
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this i project.
	 *
	 * @param status the status of this i project
	 */
	public void setStatus(String status);

	/**
	 * Returns the link of this i project.
	 *
	 * @return the link of this i project
	 */
	@AutoEscape
	public String getLink();

	/**
	 * Sets the link of this i project.
	 *
	 * @param link the link of this i project
	 */
	public void setLink(String link);

	/**
	 * Returns the departments of this i project.
	 *
	 * @return the departments of this i project
	 */
	@AutoEscape
	public String getDepartments();

	/**
	 * Sets the departments of this i project.
	 *
	 * @param departments the departments of this i project
	 */
	public void setDepartments(String departments);

	/**
	 * Returns the date added of this i project.
	 *
	 * @return the date added of this i project
	 */
	public Date getDateAdded();

	/**
	 * Sets the date added of this i project.
	 *
	 * @param dateAdded the date added of this i project
	 */
	public void setDateAdded(Date dateAdded);

	/**
	 * Returns the date modified of this i project.
	 *
	 * @return the date modified of this i project
	 */
	public Date getDateModified();

	/**
	 * Sets the date modified of this i project.
	 *
	 * @param dateModified the date modified of this i project
	 */
	public void setDateModified(Date dateModified);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(iProject iProject);

	public int hashCode();

	public CacheModel<iProject> toCacheModel();

	public iProject toEscapedModel();

	public String toString();

	public String toXmlString();
}