/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.asu.poly.iProjects.student.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the availability service. Represents a row in the &quot;poly_availability&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.asu.poly.iProjects.student.model.impl.availabilityModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.asu.poly.iProjects.student.model.impl.availabilityImpl}.
 * </p>
 *
 * @author Shruthi
 * @see availability
 * @see com.asu.poly.iProjects.student.model.impl.availabilityImpl
 * @see com.asu.poly.iProjects.student.model.impl.availabilityModelImpl
 * @generated
 */
public interface availabilityModel extends BaseModel<availability> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a availability model instance should use the {@link availability} interface instead.
	 */

	/**
	 * Returns the primary key of this availability.
	 *
	 * @return the primary key of this availability
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this availability.
	 *
	 * @param primaryKey the primary key of this availability
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the studentid of this availability.
	 *
	 * @return the studentid of this availability
	 */
	public long getStudentid();

	/**
	 * Sets the studentid of this availability.
	 *
	 * @param studentid the studentid of this availability
	 */
	public void setStudentid(long studentid);

	/**
	 * Returns the asuriteid of this availability.
	 *
	 * @return the asuriteid of this availability
	 */
	@AutoEscape
	public String getAsuriteid();

	/**
	 * Sets the asuriteid of this availability.
	 *
	 * @param asuriteid the asuriteid of this availability
	 */
	public void setAsuriteid(String asuriteid);

	/**
	 * Returns the mon8to9 of this availability.
	 *
	 * @return the mon8to9 of this availability
	 */
	@AutoEscape
	public String getMon8to9();

	/**
	 * Sets the mon8to9 of this availability.
	 *
	 * @param mon8to9 the mon8to9 of this availability
	 */
	public void setMon8to9(String mon8to9);

	/**
	 * Returns the mon9to10 of this availability.
	 *
	 * @return the mon9to10 of this availability
	 */
	@AutoEscape
	public String getMon9to10();

	/**
	 * Sets the mon9to10 of this availability.
	 *
	 * @param mon9to10 the mon9to10 of this availability
	 */
	public void setMon9to10(String mon9to10);

	/**
	 * Returns the mon10to11 of this availability.
	 *
	 * @return the mon10to11 of this availability
	 */
	@AutoEscape
	public String getMon10to11();

	/**
	 * Sets the mon10to11 of this availability.
	 *
	 * @param mon10to11 the mon10to11 of this availability
	 */
	public void setMon10to11(String mon10to11);

	/**
	 * Returns the mon11to12 of this availability.
	 *
	 * @return the mon11to12 of this availability
	 */
	@AutoEscape
	public String getMon11to12();

	/**
	 * Sets the mon11to12 of this availability.
	 *
	 * @param mon11to12 the mon11to12 of this availability
	 */
	public void setMon11to12(String mon11to12);

	/**
	 * Returns the mon12to1 of this availability.
	 *
	 * @return the mon12to1 of this availability
	 */
	@AutoEscape
	public String getMon12to1();

	/**
	 * Sets the mon12to1 of this availability.
	 *
	 * @param mon12to1 the mon12to1 of this availability
	 */
	public void setMon12to1(String mon12to1);

	/**
	 * Returns the mon1to2 of this availability.
	 *
	 * @return the mon1to2 of this availability
	 */
	@AutoEscape
	public String getMon1to2();

	/**
	 * Sets the mon1to2 of this availability.
	 *
	 * @param mon1to2 the mon1to2 of this availability
	 */
	public void setMon1to2(String mon1to2);

	/**
	 * Returns the mon2to3 of this availability.
	 *
	 * @return the mon2to3 of this availability
	 */
	@AutoEscape
	public String getMon2to3();

	/**
	 * Sets the mon2to3 of this availability.
	 *
	 * @param mon2to3 the mon2to3 of this availability
	 */
	public void setMon2to3(String mon2to3);

	/**
	 * Returns the mon3to4 of this availability.
	 *
	 * @return the mon3to4 of this availability
	 */
	@AutoEscape
	public String getMon3to4();

	/**
	 * Sets the mon3to4 of this availability.
	 *
	 * @param mon3to4 the mon3to4 of this availability
	 */
	public void setMon3to4(String mon3to4);

	/**
	 * Returns the mon4to5 of this availability.
	 *
	 * @return the mon4to5 of this availability
	 */
	@AutoEscape
	public String getMon4to5();

	/**
	 * Sets the mon4to5 of this availability.
	 *
	 * @param mon4to5 the mon4to5 of this availability
	 */
	public void setMon4to5(String mon4to5);

	/**
	 * Returns the tue8to9 of this availability.
	 *
	 * @return the tue8to9 of this availability
	 */
	@AutoEscape
	public String getTue8to9();

	/**
	 * Sets the tue8to9 of this availability.
	 *
	 * @param tue8to9 the tue8to9 of this availability
	 */
	public void setTue8to9(String tue8to9);

	/**
	 * Returns the tue9to10 of this availability.
	 *
	 * @return the tue9to10 of this availability
	 */
	@AutoEscape
	public String getTue9to10();

	/**
	 * Sets the tue9to10 of this availability.
	 *
	 * @param tue9to10 the tue9to10 of this availability
	 */
	public void setTue9to10(String tue9to10);

	/**
	 * Returns the tue10to11 of this availability.
	 *
	 * @return the tue10to11 of this availability
	 */
	@AutoEscape
	public String getTue10to11();

	/**
	 * Sets the tue10to11 of this availability.
	 *
	 * @param tue10to11 the tue10to11 of this availability
	 */
	public void setTue10to11(String tue10to11);

	/**
	 * Returns the tue11to12 of this availability.
	 *
	 * @return the tue11to12 of this availability
	 */
	@AutoEscape
	public String getTue11to12();

	/**
	 * Sets the tue11to12 of this availability.
	 *
	 * @param tue11to12 the tue11to12 of this availability
	 */
	public void setTue11to12(String tue11to12);

	/**
	 * Returns the tue12to1 of this availability.
	 *
	 * @return the tue12to1 of this availability
	 */
	@AutoEscape
	public String getTue12to1();

	/**
	 * Sets the tue12to1 of this availability.
	 *
	 * @param tue12to1 the tue12to1 of this availability
	 */
	public void setTue12to1(String tue12to1);

	/**
	 * Returns the tue1to2 of this availability.
	 *
	 * @return the tue1to2 of this availability
	 */
	@AutoEscape
	public String getTue1to2();

	/**
	 * Sets the tue1to2 of this availability.
	 *
	 * @param tue1to2 the tue1to2 of this availability
	 */
	public void setTue1to2(String tue1to2);

	/**
	 * Returns the tue2to3 of this availability.
	 *
	 * @return the tue2to3 of this availability
	 */
	@AutoEscape
	public String getTue2to3();

	/**
	 * Sets the tue2to3 of this availability.
	 *
	 * @param tue2to3 the tue2to3 of this availability
	 */
	public void setTue2to3(String tue2to3);

	/**
	 * Returns the tue3to4 of this availability.
	 *
	 * @return the tue3to4 of this availability
	 */
	@AutoEscape
	public String getTue3to4();

	/**
	 * Sets the tue3to4 of this availability.
	 *
	 * @param tue3to4 the tue3to4 of this availability
	 */
	public void setTue3to4(String tue3to4);

	/**
	 * Returns the tue4to5 of this availability.
	 *
	 * @return the tue4to5 of this availability
	 */
	@AutoEscape
	public String getTue4to5();

	/**
	 * Sets the tue4to5 of this availability.
	 *
	 * @param tue4to5 the tue4to5 of this availability
	 */
	public void setTue4to5(String tue4to5);

	/**
	 * Returns the wed8to9 of this availability.
	 *
	 * @return the wed8to9 of this availability
	 */
	@AutoEscape
	public String getWed8to9();

	/**
	 * Sets the wed8to9 of this availability.
	 *
	 * @param wed8to9 the wed8to9 of this availability
	 */
	public void setWed8to9(String wed8to9);

	/**
	 * Returns the wed9to10 of this availability.
	 *
	 * @return the wed9to10 of this availability
	 */
	@AutoEscape
	public String getWed9to10();

	/**
	 * Sets the wed9to10 of this availability.
	 *
	 * @param wed9to10 the wed9to10 of this availability
	 */
	public void setWed9to10(String wed9to10);

	/**
	 * Returns the wed10to11 of this availability.
	 *
	 * @return the wed10to11 of this availability
	 */
	@AutoEscape
	public String getWed10to11();

	/**
	 * Sets the wed10to11 of this availability.
	 *
	 * @param wed10to11 the wed10to11 of this availability
	 */
	public void setWed10to11(String wed10to11);

	/**
	 * Returns the wed11to12 of this availability.
	 *
	 * @return the wed11to12 of this availability
	 */
	@AutoEscape
	public String getWed11to12();

	/**
	 * Sets the wed11to12 of this availability.
	 *
	 * @param wed11to12 the wed11to12 of this availability
	 */
	public void setWed11to12(String wed11to12);

	/**
	 * Returns the wed12to1 of this availability.
	 *
	 * @return the wed12to1 of this availability
	 */
	@AutoEscape
	public String getWed12to1();

	/**
	 * Sets the wed12to1 of this availability.
	 *
	 * @param wed12to1 the wed12to1 of this availability
	 */
	public void setWed12to1(String wed12to1);

	/**
	 * Returns the wed1to2 of this availability.
	 *
	 * @return the wed1to2 of this availability
	 */
	@AutoEscape
	public String getWed1to2();

	/**
	 * Sets the wed1to2 of this availability.
	 *
	 * @param wed1to2 the wed1to2 of this availability
	 */
	public void setWed1to2(String wed1to2);

	/**
	 * Returns the wed2to3 of this availability.
	 *
	 * @return the wed2to3 of this availability
	 */
	@AutoEscape
	public String getWed2to3();

	/**
	 * Sets the wed2to3 of this availability.
	 *
	 * @param wed2to3 the wed2to3 of this availability
	 */
	public void setWed2to3(String wed2to3);

	/**
	 * Returns the wed3to4 of this availability.
	 *
	 * @return the wed3to4 of this availability
	 */
	@AutoEscape
	public String getWed3to4();

	/**
	 * Sets the wed3to4 of this availability.
	 *
	 * @param wed3to4 the wed3to4 of this availability
	 */
	public void setWed3to4(String wed3to4);

	/**
	 * Returns the wed4to5 of this availability.
	 *
	 * @return the wed4to5 of this availability
	 */
	@AutoEscape
	public String getWed4to5();

	/**
	 * Sets the wed4to5 of this availability.
	 *
	 * @param wed4to5 the wed4to5 of this availability
	 */
	public void setWed4to5(String wed4to5);

	/**
	 * Returns the thu8to9 of this availability.
	 *
	 * @return the thu8to9 of this availability
	 */
	@AutoEscape
	public String getThu8to9();

	/**
	 * Sets the thu8to9 of this availability.
	 *
	 * @param thu8to9 the thu8to9 of this availability
	 */
	public void setThu8to9(String thu8to9);

	/**
	 * Returns the thu9to10 of this availability.
	 *
	 * @return the thu9to10 of this availability
	 */
	@AutoEscape
	public String getThu9to10();

	/**
	 * Sets the thu9to10 of this availability.
	 *
	 * @param thu9to10 the thu9to10 of this availability
	 */
	public void setThu9to10(String thu9to10);

	/**
	 * Returns the thu10to11 of this availability.
	 *
	 * @return the thu10to11 of this availability
	 */
	@AutoEscape
	public String getThu10to11();

	/**
	 * Sets the thu10to11 of this availability.
	 *
	 * @param thu10to11 the thu10to11 of this availability
	 */
	public void setThu10to11(String thu10to11);

	/**
	 * Returns the thu11to12 of this availability.
	 *
	 * @return the thu11to12 of this availability
	 */
	@AutoEscape
	public String getThu11to12();

	/**
	 * Sets the thu11to12 of this availability.
	 *
	 * @param thu11to12 the thu11to12 of this availability
	 */
	public void setThu11to12(String thu11to12);

	/**
	 * Returns the thu12to1 of this availability.
	 *
	 * @return the thu12to1 of this availability
	 */
	@AutoEscape
	public String getThu12to1();

	/**
	 * Sets the thu12to1 of this availability.
	 *
	 * @param thu12to1 the thu12to1 of this availability
	 */
	public void setThu12to1(String thu12to1);

	/**
	 * Returns the thu1to2 of this availability.
	 *
	 * @return the thu1to2 of this availability
	 */
	@AutoEscape
	public String getThu1to2();

	/**
	 * Sets the thu1to2 of this availability.
	 *
	 * @param thu1to2 the thu1to2 of this availability
	 */
	public void setThu1to2(String thu1to2);

	/**
	 * Returns the thu2to3 of this availability.
	 *
	 * @return the thu2to3 of this availability
	 */
	@AutoEscape
	public String getThu2to3();

	/**
	 * Sets the thu2to3 of this availability.
	 *
	 * @param thu2to3 the thu2to3 of this availability
	 */
	public void setThu2to3(String thu2to3);

	/**
	 * Returns the thu3to4 of this availability.
	 *
	 * @return the thu3to4 of this availability
	 */
	@AutoEscape
	public String getThu3to4();

	/**
	 * Sets the thu3to4 of this availability.
	 *
	 * @param thu3to4 the thu3to4 of this availability
	 */
	public void setThu3to4(String thu3to4);

	/**
	 * Returns the thu4to5 of this availability.
	 *
	 * @return the thu4to5 of this availability
	 */
	@AutoEscape
	public String getThu4to5();

	/**
	 * Sets the thu4to5 of this availability.
	 *
	 * @param thu4to5 the thu4to5 of this availability
	 */
	public void setThu4to5(String thu4to5);

	/**
	 * Returns the fri8to9 of this availability.
	 *
	 * @return the fri8to9 of this availability
	 */
	@AutoEscape
	public String getFri8to9();

	/**
	 * Sets the fri8to9 of this availability.
	 *
	 * @param fri8to9 the fri8to9 of this availability
	 */
	public void setFri8to9(String fri8to9);

	/**
	 * Returns the fri9to10 of this availability.
	 *
	 * @return the fri9to10 of this availability
	 */
	@AutoEscape
	public String getFri9to10();

	/**
	 * Sets the fri9to10 of this availability.
	 *
	 * @param fri9to10 the fri9to10 of this availability
	 */
	public void setFri9to10(String fri9to10);

	/**
	 * Returns the fri10to11 of this availability.
	 *
	 * @return the fri10to11 of this availability
	 */
	@AutoEscape
	public String getFri10to11();

	/**
	 * Sets the fri10to11 of this availability.
	 *
	 * @param fri10to11 the fri10to11 of this availability
	 */
	public void setFri10to11(String fri10to11);

	/**
	 * Returns the fri11to12 of this availability.
	 *
	 * @return the fri11to12 of this availability
	 */
	@AutoEscape
	public String getFri11to12();

	/**
	 * Sets the fri11to12 of this availability.
	 *
	 * @param fri11to12 the fri11to12 of this availability
	 */
	public void setFri11to12(String fri11to12);

	/**
	 * Returns the fri12to1 of this availability.
	 *
	 * @return the fri12to1 of this availability
	 */
	@AutoEscape
	public String getFri12to1();

	/**
	 * Sets the fri12to1 of this availability.
	 *
	 * @param fri12to1 the fri12to1 of this availability
	 */
	public void setFri12to1(String fri12to1);

	/**
	 * Returns the fri1to2 of this availability.
	 *
	 * @return the fri1to2 of this availability
	 */
	@AutoEscape
	public String getFri1to2();

	/**
	 * Sets the fri1to2 of this availability.
	 *
	 * @param fri1to2 the fri1to2 of this availability
	 */
	public void setFri1to2(String fri1to2);

	/**
	 * Returns the fri2to3 of this availability.
	 *
	 * @return the fri2to3 of this availability
	 */
	@AutoEscape
	public String getFri2to3();

	/**
	 * Sets the fri2to3 of this availability.
	 *
	 * @param fri2to3 the fri2to3 of this availability
	 */
	public void setFri2to3(String fri2to3);

	/**
	 * Returns the fri3to4 of this availability.
	 *
	 * @return the fri3to4 of this availability
	 */
	@AutoEscape
	public String getFri3to4();

	/**
	 * Sets the fri3to4 of this availability.
	 *
	 * @param fri3to4 the fri3to4 of this availability
	 */
	public void setFri3to4(String fri3to4);

	/**
	 * Returns the fri4to5 of this availability.
	 *
	 * @return the fri4to5 of this availability
	 */
	@AutoEscape
	public String getFri4to5();

	/**
	 * Sets the fri4to5 of this availability.
	 *
	 * @param fri4to5 the fri4to5 of this availability
	 */
	public void setFri4to5(String fri4to5);

	/**
	 * Returns the sat8to9 of this availability.
	 *
	 * @return the sat8to9 of this availability
	 */
	@AutoEscape
	public String getSat8to9();

	/**
	 * Sets the sat8to9 of this availability.
	 *
	 * @param sat8to9 the sat8to9 of this availability
	 */
	public void setSat8to9(String sat8to9);

	/**
	 * Returns the sat9to10 of this availability.
	 *
	 * @return the sat9to10 of this availability
	 */
	@AutoEscape
	public String getSat9to10();

	/**
	 * Sets the sat9to10 of this availability.
	 *
	 * @param sat9to10 the sat9to10 of this availability
	 */
	public void setSat9to10(String sat9to10);

	/**
	 * Returns the sat10to11 of this availability.
	 *
	 * @return the sat10to11 of this availability
	 */
	@AutoEscape
	public String getSat10to11();

	/**
	 * Sets the sat10to11 of this availability.
	 *
	 * @param sat10to11 the sat10to11 of this availability
	 */
	public void setSat10to11(String sat10to11);

	/**
	 * Returns the sat11to12 of this availability.
	 *
	 * @return the sat11to12 of this availability
	 */
	@AutoEscape
	public String getSat11to12();

	/**
	 * Sets the sat11to12 of this availability.
	 *
	 * @param sat11to12 the sat11to12 of this availability
	 */
	public void setSat11to12(String sat11to12);

	/**
	 * Returns the sat12to1 of this availability.
	 *
	 * @return the sat12to1 of this availability
	 */
	@AutoEscape
	public String getSat12to1();

	/**
	 * Sets the sat12to1 of this availability.
	 *
	 * @param sat12to1 the sat12to1 of this availability
	 */
	public void setSat12to1(String sat12to1);

	/**
	 * Returns the sat1to2 of this availability.
	 *
	 * @return the sat1to2 of this availability
	 */
	@AutoEscape
	public String getSat1to2();

	/**
	 * Sets the sat1to2 of this availability.
	 *
	 * @param sat1to2 the sat1to2 of this availability
	 */
	public void setSat1to2(String sat1to2);

	/**
	 * Returns the sat2to3 of this availability.
	 *
	 * @return the sat2to3 of this availability
	 */
	@AutoEscape
	public String getSat2to3();

	/**
	 * Sets the sat2to3 of this availability.
	 *
	 * @param sat2to3 the sat2to3 of this availability
	 */
	public void setSat2to3(String sat2to3);

	/**
	 * Returns the sat3to4 of this availability.
	 *
	 * @return the sat3to4 of this availability
	 */
	@AutoEscape
	public String getSat3to4();

	/**
	 * Sets the sat3to4 of this availability.
	 *
	 * @param sat3to4 the sat3to4 of this availability
	 */
	public void setSat3to4(String sat3to4);

	/**
	 * Returns the sat4to5 of this availability.
	 *
	 * @return the sat4to5 of this availability
	 */
	@AutoEscape
	public String getSat4to5();

	/**
	 * Sets the sat4to5 of this availability.
	 *
	 * @param sat4to5 the sat4to5 of this availability
	 */
	public void setSat4to5(String sat4to5);

	/**
	 * Returns the sun8to9 of this availability.
	 *
	 * @return the sun8to9 of this availability
	 */
	@AutoEscape
	public String getSun8to9();

	/**
	 * Sets the sun8to9 of this availability.
	 *
	 * @param sun8to9 the sun8to9 of this availability
	 */
	public void setSun8to9(String sun8to9);

	/**
	 * Returns the sun9to10 of this availability.
	 *
	 * @return the sun9to10 of this availability
	 */
	@AutoEscape
	public String getSun9to10();

	/**
	 * Sets the sun9to10 of this availability.
	 *
	 * @param sun9to10 the sun9to10 of this availability
	 */
	public void setSun9to10(String sun9to10);

	/**
	 * Returns the sun10to11 of this availability.
	 *
	 * @return the sun10to11 of this availability
	 */
	@AutoEscape
	public String getSun10to11();

	/**
	 * Sets the sun10to11 of this availability.
	 *
	 * @param sun10to11 the sun10to11 of this availability
	 */
	public void setSun10to11(String sun10to11);

	/**
	 * Returns the sun11to12 of this availability.
	 *
	 * @return the sun11to12 of this availability
	 */
	@AutoEscape
	public String getSun11to12();

	/**
	 * Sets the sun11to12 of this availability.
	 *
	 * @param sun11to12 the sun11to12 of this availability
	 */
	public void setSun11to12(String sun11to12);

	/**
	 * Returns the sun12to1 of this availability.
	 *
	 * @return the sun12to1 of this availability
	 */
	@AutoEscape
	public String getSun12to1();

	/**
	 * Sets the sun12to1 of this availability.
	 *
	 * @param sun12to1 the sun12to1 of this availability
	 */
	public void setSun12to1(String sun12to1);

	/**
	 * Returns the sun1to2 of this availability.
	 *
	 * @return the sun1to2 of this availability
	 */
	@AutoEscape
	public String getSun1to2();

	/**
	 * Sets the sun1to2 of this availability.
	 *
	 * @param sun1to2 the sun1to2 of this availability
	 */
	public void setSun1to2(String sun1to2);

	/**
	 * Returns the sun2to3 of this availability.
	 *
	 * @return the sun2to3 of this availability
	 */
	@AutoEscape
	public String getSun2to3();

	/**
	 * Sets the sun2to3 of this availability.
	 *
	 * @param sun2to3 the sun2to3 of this availability
	 */
	public void setSun2to3(String sun2to3);

	/**
	 * Returns the sun3to4 of this availability.
	 *
	 * @return the sun3to4 of this availability
	 */
	@AutoEscape
	public String getSun3to4();

	/**
	 * Sets the sun3to4 of this availability.
	 *
	 * @param sun3to4 the sun3to4 of this availability
	 */
	public void setSun3to4(String sun3to4);

	/**
	 * Returns the sun4to5 of this availability.
	 *
	 * @return the sun4to5 of this availability
	 */
	@AutoEscape
	public String getSun4to5();

	/**
	 * Sets the sun4to5 of this availability.
	 *
	 * @param sun4to5 the sun4to5 of this availability
	 */
	public void setSun4to5(String sun4to5);

	/**
	 * Returns the create date of this availability.
	 *
	 * @return the create date of this availability
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this availability.
	 *
	 * @param createDate the create date of this availability
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this availability.
	 *
	 * @return the modified date of this availability
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this availability.
	 *
	 * @param modifiedDate the modified date of this availability
	 */
	public void setModifiedDate(Date modifiedDate);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(availability availability);

	public int hashCode();

	public CacheModel<availability> toCacheModel();

	public availability toEscapedModel();

	public String toString();

	public String toXmlString();
}